<script setup lang="ts">
import { computed, onMounted, shallowRef } from "vue";
import { evidenceMatricesApi, type EvidenceMatrix, type MatrixCell } from "../../api/evidenceMatrices";
import EvidenceMatrixInspector from "../../components/evidence-matrix/EvidenceMatrixInspector.vue";
import EvidenceMatrixTable from "../../components/evidence-matrix/EvidenceMatrixTable.vue";
import { researchContextsApi, type ResearchContext } from "../../api/researchContexts";

const matrices = shallowRef<EvidenceMatrix[]>([]); const matrix = shallowRef<EvidenceMatrix | null>(null); const selectedCell = shallowRef<MatrixCell | null>(null); const loading = shallowRef(false); const saving = shallowRef(false); const error = shallowRef(""); const newName = shallowRef(""); const newDescription = shallowRef("");
const contexts = shallowRef<ResearchContext[]>([]); const selectedContextId = shallowRef<number | null>(null);
const hasMatrix = computed(() => matrix.value !== null);
async function load(matrixId?: number): Promise<void> { loading.value = true; error.value = ""; try { const [page, loadedContexts] = await Promise.all([evidenceMatricesApi.list(), researchContextsApi.list()]); matrices.value = page.items; contexts.value = loadedContexts; const target = matrixId ?? page.items[0]?.id; matrix.value = target ? await evidenceMatricesApi.get(target) : null; selectedCell.value = null; } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法读取证据矩阵。"; } finally { loading.value = false; } }
async function create(): Promise<void> { if (!newName.value.trim()) return; saving.value = true; error.value = ""; try { const created = await evidenceMatricesApi.create(newName.value.trim(), newDescription.value.trim(), selectedContextId.value); newName.value = ""; newDescription.value = ""; await load(created.id); } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法创建证据矩阵。"; } finally { saving.value = false; } }
async function saveCell(documentId: number, fieldKey: string, value: string): Promise<void> { if (!matrix.value) return; saving.value = true; try { matrix.value = await evidenceMatricesApi.updateCell(matrix.value.id, documentId, fieldKey, value); selectedCell.value = matrix.value.cells.find((cell) => cell.document_id === documentId && cell.field_key === fieldKey) ?? null; } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法保存单元格。"; } finally { saving.value = false; } }
async function regenerate(): Promise<void> { if (!matrix.value) return; saving.value = true; try { matrix.value = await evidenceMatricesApi.regenerate(matrix.value.id); } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法重新生成矩阵。"; } finally { saving.value = false; } }
onMounted(() => void load());
</script>

<template>
  <main class="matrix-layout"><section class="matrix"><header class="page-header"><div><p class="eyebrow">EVIDENCE MATRIX</p><h1>证据矩阵</h1><p>矩阵只展示后端返回的文档、单元格和可追溯来源；没有来源的字段会明确显示为缺失。</p></div><select v-if="matrices.length" :value="matrix?.id" aria-label="选择证据矩阵" @change="load(Number(($event.target as HTMLSelectElement).value))"><option v-for="item in matrices" :key="item.id" :value="item.id">{{ item.name }}</option></select></header><form class="create-form" @submit.prevent="create"><input v-model.trim="newName" :disabled="saving" placeholder="新矩阵名称" maxlength="200"><input v-model.trim="newDescription" :disabled="saving" placeholder="说明（可选）" maxlength="4000"><select v-model="selectedContextId" aria-label="研究上下文"><option :value="null">未关联研究上下文</option><option v-for="context in contexts" :key="context.id" :value="context.id">{{ context.name }}</option></select><button :disabled="saving || !newName">创建矩阵</button></form><p v-if="error" class="error">{{ error }}</p><p v-if="loading">正在读取证据矩阵…</p><template v-else-if="hasMatrix"><div class="toolbar"><span>研究上下文 {{ matrix?.research_context_id ?? "未关联" }} · 版本 {{ matrix?.version }} · {{ matrix?.documents.length }} 篇文档</span><button :disabled="saving" @click="regenerate">重新生成未人工修改的单元格</button></div><EvidenceMatrixTable :matrix="matrix!" :saving="saving" @select-cell="selectedCell = $event" @save-cell="saveCell" /></template><section v-else class="empty"><h2>尚无证据矩阵</h2><p>创建一个矩阵后，再从已解析的文档中加入 3–10 篇论文。</p></section></section><EvidenceMatrixInspector :cell="selectedCell" /></main>
</template>

<style scoped>
.matrix-layout{display:grid;grid-template-columns:minmax(0,1fr) 300px;min-height:calc(100vh - 72px)}.matrix{padding:2rem 1.4rem}.page-header{display:flex;justify-content:space-between;gap:1rem}.eyebrow{margin:0;color:var(--color-primary);font-size:.72rem;font-weight:900;letter-spacing:.12em}.page-header h1{margin:.25rem 0;font-size:2rem}.page-header p{max-width:720px;color:var(--text-muted);line-height:1.55}.page-header select,.create-form input{padding:.55rem .65rem;border:1px solid var(--border-subtle);border-radius:7px;background:var(--paper);font:inherit}.create-form{display:grid;grid-template-columns:minmax(160px,1fr) minmax(220px,2fr) auto;gap:.55rem;margin:1.25rem 0}.create-form button,.toolbar button{border:0;border-radius:7px;padding:.55rem .75rem;background:var(--color-primary);color:white;font:inherit;font-weight:750}.toolbar{display:flex;justify-content:space-between;align-items:center;gap:1rem;margin-bottom:.8rem;color:var(--text-muted);font-size:.85rem}.error{padding:.7rem;border-radius:7px;background:var(--color-danger-soft);color:var(--color-danger)}.empty{padding:2rem;border:1px dashed var(--border-strong);border-radius:var(--radius-md);background:var(--surface-raised)}.empty p{color:var(--text-muted)}@media(max-width:900px){.matrix-layout{grid-template-columns:1fr}.page-header{display:block}.page-header select{margin-top:.5rem}.create-form{grid-template-columns:1fr}.toolbar{align-items:flex-start;flex-direction:column}}
</style>
