<script setup lang="ts">
import { computed, shallowRef } from "vue";
import { useRoute } from "vue-router";
const route = useRoute(); const activeSection = shallowRef("汇报目的"); const speakerNotes = shallowRef(""); const personalNote = shallowRef("");
const sections = ["汇报目的", "研究背景", "材料与证据", "讨论问题", "待确认项"];
const selectedTitle = computed(() => String(route.params.id).startsWith("local-") ? "未命名组会草稿" : "组会草稿");
</script>

<template><main class="editor"><header class="editor-header"><div><p class="eyebrow">PRESENTATION EDITOR · MOCK</p><h1>{{ selectedTitle }}</h1><p>保存状态：仅本地原型 · 版本：v0</p></div><div class="header-actions"><button>生成提纲（原型）</button><button>引用核验（未接入）</button><button>导出 Markdown（原型）</button><button class="primary">导出 PPT 大纲（原型）</button></div></header><div class="editor-grid"><aside class="outline"><p class="eyebrow">OUTLINE</p><button v-for="section in sections" :key="section" :class="{ active: section === activeSection }" @click="activeSection = section">{{ section }}</button><hr><small>材料：未接入</small><small>版本：本地 v0</small></aside><section class="canvas"><p class="eyebrow">{{ activeSection }}</p><h2>汇报提纲</h2><div class="draft-block">本地原型不会自动生成实验数据、论文结论或引用。请在接入真实材料后补充本节内容。</div><label>讲述备注<textarea v-model="speakerNotes" placeholder="记录讲述重点（仅本地）"></textarea></label><label>导师可能提问<textarea placeholder="待讨论问题"></textarea></label><label>个人备注<textarea v-model="personalNote" placeholder="记录需要确认的事项"></textarea></label></section><aside class="evidence"><p class="eyebrow">EVIDENCE · MOCK</p><h2>证据与来源</h2><p>论文证据：未接入</p><p>页码：未接入</p><p>原文：未接入</p><p>待确认项：请补充材料来源后核验。</p><div class="origin">内容来源：待确认</div></aside></div></main></template>

<style scoped>.editor{min-height:calc(100vh - 65px)}.editor-header{display:flex;justify-content:space-between;gap:1rem;padding:1.25rem 1.4rem;border-bottom:1px solid var(--border-subtle);background:var(--paper)}.eyebrow{margin:0;color:var(--color-primary);font-size:.72rem;font-weight:900;letter-spacing:.12em}.editor-header h1{margin:.25rem 0;font-size:1.65rem}.editor-header p:last-child{margin:0;color:var(--text-muted)}.header-actions{display:flex;align-content:start;flex-wrap:wrap;justify-content:flex-end;gap:.45rem}.header-actions button{border:1px solid var(--border-strong);border-radius:6px;padding:.45rem .55rem;background:var(--paper);font-weight:700}.header-actions .primary{border-color:var(--color-primary);background:var(--color-primary);color:#fff}.editor-grid{display:grid;grid-template-columns:210px minmax(0,1fr) 280px;min-height:calc(100vh - 162px)}.outline,.evidence{padding:1.1rem;border-color:var(--border-subtle);background:var(--surface-raised)}.outline{border-right:1px solid var(--border-subtle)}.outline button{display:block;width:100%;margin:.3rem 0;padding:.55rem;border:0;background:transparent;text-align:left}.outline button.active{border-left:3px solid var(--color-primary);background:var(--surface-muted);color:var(--color-primary);font-weight:800}.outline small{display:block;margin:.6rem 0;color:var(--text-muted)}.canvas{padding:1.4rem;max-width:820px}.canvas h2{margin:.25rem 0}.draft-block{margin:1rem 0;padding:1rem;border-left:3px solid var(--color-warning);background:var(--color-warning-soft);color:var(--color-warning);line-height:1.6}.canvas label{display:grid;gap:.35rem;margin-top:1rem;font-weight:800}.canvas textarea{min-height:95px;padding:.7rem;border:1px solid var(--border-subtle);border-radius:6px;background:var(--paper);font:inherit}.evidence{border-left:1px solid var(--border-subtle)}.evidence h2{margin:.25rem 0}.evidence p{color:var(--text-muted);line-height:1.55}.origin{margin-top:1rem;padding:.6rem;background:var(--surface-muted);font-size:.85rem}@media(max-width:980px){.editor-grid{grid-template-columns:180px minmax(0,1fr)}.evidence{display:none}}@media(max-width:720px){.editor-header{display:block}.header-actions{justify-content:start;margin-top:.8rem}.editor-grid{grid-template-columns:1fr}.outline{border-right:0;border-bottom:1px solid var(--border-subtle)}.outline button{display:inline-block;width:auto}.canvas{padding:1rem}}</style>
