<script setup lang="ts">
import { computed, onMounted, shallowRef } from "vue";
import { useRoute, useRouter } from "vue-router";
import { literatureSearchApi, type LiteratureSearchTask, type SearchSort } from "../../api/literatureSearch";
import PaperResults from "../../components/PaperResults/PaperResults.vue";
import ExportMenu from "../../components/literature-results/ExportMenu.vue";
import ResultsFilterSidebar from "../../components/literature-results/ResultsFilterSidebar.vue";
import DuplicateReviewDrawer from "../../components/literature/DuplicateReviewDrawer.vue";
import { DEFAULT_PAGE_SIZE, useLiteratureResults } from "../../composables/useLiteratureResults";
import { useResultDeduplication } from "../../composables/useResultDeduplication";
import { researchContextsApi } from "../../api/researchContexts";

const props=withDefaults(defineProps<{resultId?:number;taskId?:number;embedded?:boolean}>(),{embedded:false});
const route=useRoute(),router=useRouter();
const resultId=props.resultId??Number(route.params.id);
const taskId=props.taskId??Number(Array.isArray(route.query.task)?route.query.task[0]:route.query.task??resultId);
const task=shallowRef<LiteratureSearchTask|null>(null),filterOpen=shallowRef(true),statusOpen=shallowRef(false),exporting=shallowRef(false),message=shallowRef(""),scoring=shallowRef(false),duplicateOpen=shallowRef(false);
const selected=shallowRef<string[]>([]),rerunning=shallowRef(false); const r=useLiteratureResults(resultId);
const deduplication=useResultDeduplication(resultId,()=>void r.reload());
const displayTitle=computed(()=>{const value=(task.value?.original_query||r.page.value?.query||"").trim();return value&&value.length<=100?value:"本次 PubMed 文献检索"});
const activeView=computed(()=>route.query.view==="reading-plan"||route.query.view==="saved"?"reading-plan":"all");
const range=computed(()=>({start:r.filteredTotal.value?(r.currentPage.value-1)*DEFAULT_PAGE_SIZE+1:0,end:Math.min(r.currentPage.value*DEFAULT_PAGE_SIZE,r.filteredTotal.value)}));
const chips=computed(()=>{const f=r.filters.value,v:string[]=[];if(f.year_from||f.year_to)v.push(`${f.year_from??"…"}–${f.year_to??"…"}`);else if(f.year)v.push(String(f.year));if(f.publication_type)v.push(f.publication_type);if(f.journal)v.push(f.journal);if(f.has_abstract)v.push("有摘要");return v});
const sorts:Array<{value:SearchSort;label:string}>=[{value:"recommended",label:"综合推荐"},{value:"popular",label:"🔥 近期热度"},{value:"newest",label:"最新发表"},{value:"article_impact",label:"文章影响力"},{value:"classic",label:"经典度"}];
function setView(view:"all"|"reading-plan"){void router.replace({query:{...route.query,view:view==="all"?undefined:view}});r.applyFilters({...r.filters.value,saved:view==="reading-plan"?true:null})}
async function ensureScoring():Promise<boolean>{
  if(r.page.value?.scoring_status==="active")return true;
  scoring.value=true;message.value="正在获取 OpenAlex 文章级指标并生成评分…";
  try{
    let contextId=task.value?.research_context_id??null;
    if(!contextId){const context=await researchContextsApi.create(task.value?.original_query||r.page.value?.query||"文献检索评分","由检索结果页为文章级排序建立");contextId=context.id;if(task.value)task.value=await literatureSearchApi.bindTaskResearchContext(task.value.id,contextId)}
    const intent=await literatureSearchApi.createResearchIntent(contextId,{topic:task.value?.original_query||r.page.value?.query||"",query:task.value?.search_string||""});
    await literatureSearchApi.createScoringRun(resultId,intent.id,false);
    for(let attempt=0;attempt<90;attempt+=1){const status=await literatureSearchApi.getScoringStatus(resultId);if(status.status==="active"){await r.reload();message.value="评分已生成，可以使用近期热度、文章影响力和经典度排序";return true}if(status.status==="failed")throw new Error(status.last_error||"评分生成失败");await new Promise(resolve=>setTimeout(resolve,1000))}
    throw new Error("评分仍在后台生成，请稍后重试");
  }catch(e){message.value=e instanceof Error?e.message:"无法生成文章评分";return false}finally{scoring.value=false}
}
async function sort(value:SearchSort){if(scoring.value)return;const requiresScore=["popular","article_impact","classic"].includes(value);const capability=r.page.value?.sort_capabilities?.[value];if(requiresScore&&(r.page.value?.scoring_status!=="active"||capability?.available===false)){if(!await ensureScoring())return}message.value="";r.applyFilters({...r.filters.value,sort:value})}
async function openDuplicates(){duplicateOpen.value=true;await deduplication.loadSummary();if(deduplication.summary.value?.has_scan)await deduplication.loadGroups("pending_resolution",0)}
function loadDuplicateGroups(status:"pending_resolution"|"all",page:number){void deduplication.loadGroups(status,(page-1)*10)}
function readStatus(value:""|"unread"|"reading"|"read"){r.applyFilters({...r.filters.value,read_status:value});statusOpen.value=false}
function clear(){r.applyFilters({...r.filters.value,year:null,year_from:null,year_to:null,publication_type:"",journal:"",author:"",has_abstract:null,saved:null,read_status:"",tags:"",jcr_quartile:"",wos_index:"",cas_quartile:"",impact_factor_min:null,cited_by_min:null})}
function select(pmid:string,checked:boolean){selected.value=checked?[...new Set([...selected.value,pmid])]:selected.value.filter(v=>v!==pmid)}
async function loadMore(){rerunning.value=true;message.value="";try{const next=await literatureSearchApi.rerunTask(taskId,500);await router.push(`/literature-search/results/${next.new_result_id}?task=${next.task.id}`)}catch(e){message.value=e instanceof Error?e.message:"无法加载更多结果"}finally{rerunning.value=false}}
async function exportResults(format:"csv"|"ris"|"bibtex"){exporting.value=true;try{const blob=await literatureSearchApi.exportResults(resultId,r.filters.value,format),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`literature-results-${resultId}.${format}`;a.click();URL.revokeObjectURL(url)}catch(e){message.value=e instanceof Error?e.message:"导出失败"}finally{exporting.value=false}}
onMounted(async()=>{if(typeof window.matchMedia==="function"&&window.matchMedia("(max-width:1199px)").matches)filterOpen.value=false;try{const explicitTask=route.query.task!=null;if(explicitTask){task.value=await literatureSearchApi.getTask(taskId)}else{const history=await literatureSearchApi.listHistory(0,100);const match=history.items.find(item=>item.latest_result_id===resultId);task.value=match?await literatureSearchApi.getTask(match.id):null}}catch{task.value=null}});
</script>

<template><main class="page results-replica" :class="{embedded:props.embedded}"><section class="layout"><div class="main replica-main results-workspace">
  <header class="context result-context research-brief"><h1 :title="task?.original_query||r.page.value?.query||''">{{displayTitle}} <span>✎</span></h1><div class="journey"><b>✓</b>研究问题<i>→</i><b>✓</b>检索意图<i>→</i><b>✓</b>策略构建<i>→</i><b>✓</b>{{r.page.value?.total_count??0}}篇结果</div><p>当前检索策略 · {{task?.model_version||"v3"}}　｜　数据库 · PubMed　｜　检索时间 · {{task?.searched_at?new Date(task.searched_at).toLocaleString("zh-CN"):"—"}}　｜　PubMed 命中 {{(r.page.value?.total_count??0).toLocaleString('en-US')}} 篇</p></header>
  <nav class="tabs result-view-tabs"><button :class="{active:activeView==='all'}" @click="setView('all')">全部文献 <b>{{r.page.value?.total_count??0}}</b></button><button :class="{active:activeView==='reading-plan'}" @click="setView('reading-plan')">阅读计划 <b>{{r.page.value?.reading_plan_total??0}}</b></button></nav>
  <section class="controls"><div class="sort"><span>排序：</span><button v-for="o in sorts" :key="o.value" :class="[{active:r.filters.value.sort===o.value},{'start-scoring':o.value==='popular'}]" :disabled="scoring" @click="sort(o.value)">{{o.label}}</button><i/><div class="status"><button :aria-expanded="statusOpen" @click="statusOpen=!statusOpen">阅读状态⌄</button><div v-if="statusOpen" class="popover"><button v-for="o in [{v:'',l:'全部文献'},{v:'unread',l:'未读'},{v:'reading',l:'阅读中'},{v:'read',l:'已读'}]" :key="o.v" @click="readStatus(o.v as ''|'unread'|'reading'|'read')">{{r.filters.value.read_status===o.v?'✓ ':''}}{{o.l}}</button></div></div><button @click="filterOpen=!filterOpen">⌄ 筛选条件</button><ExportMenu :exporting="exporting" @export="exportResults"/><button class="more-actions inline-more-actions" @click="openDuplicates">检查重复论文</button></div><div class="chips result-toolbar-chips"><span>已筛选：</span><span v-if="!chips.length" class="chip">全部结果</span><span v-for="c in chips.slice(0,4)" :key="c" class="chip">{{c}} ×</span><button @click="clear">清除全部</button></div><p v-if="message" class="message">{{message}}</p></section>
  <div v-if="selected.length" class="bulk"><b>已选择 {{selected.length}} 篇</b><button @click="selected.forEach(p=>r.updateState(p,{in_reading_plan:true,saved:true}))">加入阅读计划</button><button @click="selected.forEach(p=>r.updateState(p,{read_status:'read'}))">标记已读</button><button @click="selected=[]">清除选择</button></div><div v-else class="head"><span>□　已选择 0 篇</span><button v-if="(r.page.value?.total_count??0)>r.filteredTotal.value&&!chips.length" class="load-more" :disabled="rerunning" @click="loadMore">{{rerunning?'正在重新检索…':`当前快照 ${r.filteredTotal.value} 篇 · 加载更多`}}</button><span>筛选后 {{r.filteredTotal.value}} 篇　 ‹　<b>{{range.start}}–{{range.end}} / {{r.filteredTotal.value}}</b>　›</span></div>
  <PaperResults :items="r.page.value?.items??[]" :result-id="resultId" :loading="r.loading.value" :updating="r.updating.value" :selected-pmids="selected" :current-page="r.currentPage.value" :page-size="DEFAULT_PAGE_SIZE" :total-pages="r.totalPages.value" :filtered-total="r.filteredTotal.value" :has-previous="r.hasPrevious.value" :has-next="r.hasNext.value" @previous-page="r.previousPage" @next-page="r.nextPage" @go-to-page="r.goToPage" @toggle-reading-plan="(p,v)=>r.updateState(p,{in_reading_plan:v,saved:v})" @toggle-read="(p,v)=>r.updateState(p,{read_status:v?'read':'unread'})" @toggle-selection="select" @library-item-updated="r.updateLibraryItem" @show-score-explanation="message='请先生成评分后查看依据'"/>
</div><ResultsFilterSidebar :open="filterOpen" :filters="r.filters.value" :facets="r.page.value?.facets" :filtered-total="r.filteredTotal.value" :disabled="r.loading.value" @apply="r.applyFilters" @close="filterOpen=false"/></section><DuplicateReviewDrawer :open="duplicateOpen" :summary="deduplication.summary.value" :groups="deduplication.groups.value" :status="deduplication.status.value" :page="deduplication.page.value" :total-pages="deduplication.totalPages.value" :loading="deduplication.loading.value" :error="deduplication.error.value" @close="duplicateOpen=false" @scan="deduplication.scan" @load-groups="loadDuplicateGroups" @resolve="(groupId,action,recordKey)=>deduplication.resolve(groupId,{action,canonical_record_key:recordKey})"/></main></template>

<style scoped>
.page{min-height:calc(100vh - 62px);background:#fff;color:#102c55}.layout{display:flex;min-width:0}.main{flex:1;min-width:0}.context{height:97px;box-sizing:border-box;padding:12px 20px;border-bottom:1px solid #e2e9f3}.context h1{margin:0 0 7px;color:#071d3d;font-size:20px;line-height:24px;font-weight:760}.context h1 span{color:#1260f6;font-size:11px}.journey{display:flex;align-items:center;gap:8px;margin-bottom:6px;color:#244a7d;font-size:10px;font-weight:650}.journey b{display:grid;width:13px;height:13px;place-items:center;border:1px solid #1762fa;border-radius:50%;color:#1762fa;font-size:7px}.journey i{color:#94a6c1;font-style:normal}.context p{margin:0;color:#667e9f;font-size:10px}.tabs{display:flex;height:51px;padding:0 8px;border-bottom:1px solid #dce5f1}.tabs button{min-width:120px;padding:0 9px;border:0;border-bottom:2px solid transparent;background:#fff;color:#263f65;font-size:13px;font-weight:700;cursor:pointer}.tabs button.active{border-color:#1762fa;color:#0759f9}.tabs b{margin-left:5px;color:#0759f9}.controls{padding:9px 8px 7px;border-bottom:1px solid #dce5f1}.sort{display:flex;align-items:center;gap:7px;color:#58708f;font-size:10px}.sort>button,.status>button{height:32px;padding:0 12px;border:1px solid #d6e1f1;border-radius:6px;background:#fff;color:#193e72;font:inherit;font-weight:650;cursor:pointer}.sort>button.active{border-color:#1762fa;background:#1762fa;color:#fff}.sort>i{flex:1}.status{position:relative}.popover{position:absolute;z-index:30;right:0;top:37px;width:145px;padding:5px;border:1px solid #dce5f1;border-radius:7px;background:#fff;box-shadow:0 10px 25px #12315c1c}.popover button{display:block;width:100%;padding:7px;border:0;background:#fff;color:#264b7c;text-align:left}.chips{display:flex;align-items:center;gap:7px;margin-top:8px;color:#6b809e;font-size:10px}.chip{padding:4px 9px;border-radius:5px;background:#eef4ff;color:#0759f9;font-weight:650}.chips button{margin-left:auto;border:0;background:transparent;color:#0759f9}.message{margin:6px 0 0;padding:5px 8px;background:#fff8e8;color:#8b5d00;font-size:10px}.bulk,.head{display:flex;align-items:center;height:43px;box-sizing:border-box;padding:0 16px;border-bottom:1px solid #dce5f1;color:#536c8e;font-size:10px}.head{justify-content:space-between}.bulk{gap:8px}.bulk button,.load-more{height:27px;border:1px solid #d3e0f4;border-radius:5px;background:#fff;color:#1754ae;font-size:10px}.load-more{margin-left:auto;margin-right:14px}@media(max-width:1199px){.layout{display:block}.sort{flex-wrap:wrap}.sort>i{display:none}}@media(max-width:720px){.tabs button{min-width:0;flex:1}.context h1{font-size:17px}.journey{display:none}.controls{overflow:auto}.sort{width:max-content}}
</style>
