<script setup lang="ts">
import { computed, onMounted, shallowRef } from "vue";
import { documentsApi, type DocumentRecord } from "../../api/documents";
import TaskList from "../../components/tasks/TaskList.vue";
const items = shallowRef<DocumentRecord[]>([]); const selected = shallowRef<DocumentRecord | null>(null); const loading = shallowRef(false); const error = shallowRef(""); const filter = shallowRef("all");
const visible = computed(() => filter.value === "all" ? items.value : items.value.filter((item) => `${item.parse_status}/${item.index_status}`.includes(filter.value)));
async function load() { loading.value = true; error.value = ""; try { items.value = (await documentsApi.list({ parseStatus: "", indexStatus: "" }, 0, 100)).items; } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法读取文档处理状态"; } finally { loading.value = false; } }
async function retryParse(id: number) { await documentsApi.retryParse(id); await load(); }
async function retryIndex(id: number) { await documentsApi.retryIndex(id); await load(); }
onMounted(load);
</script>
<template><main class="layout"><section class="page"><header class="header"><div><p class="eyebrow">TASK CENTER · LIVE BOUNDARY</p><h1>任务中心</h1><p>当前仅展示已有接口返回的文档解析与索引状态；通用任务、导出、评测和 Agent 执行尚未接入。</p></div><button @click="load">刷新状态</button></header><div class="filters"><button :class="{ active: filter === 'all' }" @click="filter = 'all'">全部</button><button :class="{ active: filter === 'failed' }" @click="filter = 'failed'">失败</button><button :class="{ active: filter === 'parsing' }" @click="filter = 'parsing'">解析中</button><button :class="{ active: filter === 'indexing' }" @click="filter = 'indexing'">索引中</button></div><p v-if="loading">正在读取真实状态…</p><p v-if="error" class="error">{{ error }}</p><TaskList :items="visible" :selected-id="selected?.id ?? null" @select="selected = $event" @retry-parse="retryParse" @retry-index="retryIndex"/></section><aside class="rail"><p class="eyebrow">TASK DETAIL · LIVE</p><h2>{{ selected ? selected.file_path : "选择一项任务" }}</h2><template v-if="selected"><p>解析：{{ selected.parse_status }} · 索引：{{ selected.index_status }}</p><p>重试次数：{{ selected.retry_count }}</p><p>开始：{{ selected.started_at || "未提供" }}</p><p>结束：{{ selected.finished_at || "未提供" }}</p><p v-if="selected.error_message" class="error">错误摘要：{{ selected.error_message }}</p><p v-else>错误摘要：未提供</p></template><p v-else>右侧只显示已接入文档状态的详情与错误摘要。</p></aside></main></template>
<style scoped>.layout{display:grid;grid-template-columns:minmax(0,1fr) 290px;min-height:calc(100vh - 65px)}.page{padding:2rem 1.4rem}.header{display:flex;justify-content:space-between;gap:1rem}.eyebrow{margin:0;color:var(--color-primary);font-size:.72rem;font-weight:900;letter-spacing:.12em}.header h1{margin:.25rem 0;font-size:2.3rem}.header p:last-child,.rail p{color:var(--text-muted);line-height:1.55}.header button,.filters button{border:1px solid var(--border-strong);border-radius:6px;padding:.5rem .7rem;background:var(--paper);font-weight:700}.filters{display:flex;gap:.45rem;flex-wrap:wrap;margin:1rem 0}.filters .active{border-color:var(--color-primary);background:var(--color-primary);color:#fff}.rail{padding:1.4rem;border-left:1px solid var(--border-subtle);background:var(--surface-raised)}.rail h2{font-size:1.1rem;word-break:break-word}.error{color:var(--color-danger)!important}@media(max-width:850px){.layout{grid-template-columns:1fr}.rail{border-left:0;border-top:1px solid var(--border-subtle)}}</style>
