<script setup lang="ts">
import { computed, shallowRef } from "vue";
import { prototypeCell, prototypeFields, prototypePapers, type PrototypeCell } from "../../mocks/comparison";
const fields = shallowRef([...prototypeFields]); const selected = shallowRef<PrototypeCell | null>(null); const edited = shallowRef<Record<string,string>>({});
const papers = computed(() => prototypePapers);
function value(fieldId:string, paperId:string) { return edited.value[`${fieldId}-${paperId}`] ?? prototypeCell(fields.value.find(item=>item.id===fieldId)!, papers.value.find(item=>item.id===paperId)! ).value; }
function edit(fieldId:string,paperId:string,event:Event) { edited.value={...edited.value,[`${fieldId}-${paperId}`]:(event.target as HTMLInputElement).value}; }
</script>
<template><main class="prototype-layout"><section class="comparison"><header><p class="eyebrow">MULTI-PAPER COMPARISON · MOCK</p><h1>多论文对比</h1><p>前端原型：真实多论文处理将在 R2 后续阶段接入。示例不代表真实文献或医学结论。</p></header><div class="toolbar"><strong>比较名称：未命名比较</strong><button>选择论文（原型）</button><button>转为证据矩阵</button><button>导出（原型）</button></div><div class="warning">研究类型当前均未提供，不能据此比较研究质量。</div><div class="table-wrap"><table><thead><tr><th>比较字段</th><th v-for="paper in papers" :key="paper.id">{{ paper.title }}<small>DOI/PMID：未接入</small></th></tr></thead><tbody><tr v-for="field in fields" :key="field.id"><th>{{ field.label }}</th><td v-for="paper in papers" :key="paper.id"><input :value="value(field.id,paper.id)" @focus="selected=prototypeCell(field,paper)" @input="edit(field.id,paper.id,$event)"/><small v-if="edited[`${field.id}-${paper.id}`]" class="human">人工修改</small></td></tr></tbody></table></div></section><aside class="context"><p class="eyebrow">CELL CONTEXT · MOCK</p><h2>当前单元格来源</h2><p>{{ selected?.value || "选择任意单元格查看状态" }}</p><p>页码：未接入</p><p>原文：未接入</p><p>编辑历史：本地原型</p></aside></main></template>
<style scoped>.prototype-layout{display:grid;grid-template-columns:minmax(0,1fr) 300px;min-height:calc(100vh - 72px)}.comparison{padding:2rem 1.4rem}.eyebrow{margin:0;color:var(--color-primary);font-size:.72rem;font-weight:900;letter-spacing:.12em}h1{margin:.25rem 0;font-size:2.3rem}.comparison header>p:last-child,.context p{color:var(--text-muted)}.toolbar{display:flex;gap:.6rem;flex-wrap:wrap;margin:1rem 0}.toolbar button{border:1px solid var(--border-strong);border-radius:8px;padding:.55rem .7rem;background:var(--paper)}.warning{padding:.7rem;border-radius:var(--radius-md);background:var(--color-warning-soft);color:var(--color-warning)}.table-wrap{overflow:auto;margin-top:1rem;border:1px solid var(--border-subtle);border-radius:var(--radius-md)}table{min-width:850px;width:100%;border-collapse:collapse;background:var(--paper)}th,td{padding:.75rem;border-bottom:1px solid var(--border-subtle);text-align:left;vertical-align:top}thead th{position:sticky;top:0;background:var(--surface-raised)}tbody th{position:sticky;left:0;background:var(--paper)}td input{width:100%;border:0;background:transparent;color:var(--text-primary)}small{display:block;margin-top:.25rem;color:var(--text-muted)}.human{color:var(--color-primary)}.context{padding:1.4rem;border-left:1px solid var(--border-subtle);background:var(--surface-raised)}@media(max-width:850px){.prototype-layout{grid-template-columns:1fr}.context{border-left:0;border-top:1px solid var(--border-subtle)}}</style>
