"""make library_items doi/pmid indexes unique

Revision ID: ee5f23856af4
Revises: f5c6d7e8f9a0
Create Date: 2026-08-06 13:34:00.055340

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee5f23856af4"
down_revision: str | Sequence[str] | None = "f5c6d7e8f9a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_library_items_doi"), table_name="library_items")
    op.create_index(op.f("ix_library_items_doi"), "library_items", ["doi"], unique=True)
    op.drop_index(op.f("ix_library_items_pmid"), table_name="library_items")
    op.create_index(
        op.f("ix_library_items_pmid"), "library_items", ["pmid"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_library_items_pmid"), table_name="library_items")
    op.create_index(
        op.f("ix_library_items_pmid"), "library_items", ["pmid"], unique=False
    )
    op.drop_index(op.f("ix_library_items_doi"), table_name="library_items")
    op.create_index(
        op.f("ix_library_items_doi"), "library_items", ["doi"], unique=False
    )
    # ### end Alembic commands ###
