import { computed, onMounted, shallowRef, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { paperLibraryApi } from "../api/paperLibrary";
import { paperResearchCenterApi, type PaperCenterData, type CenterTask } from "../api/paperResearchCenter";

const stageLabels: Record<string, string> = { problem_definition: "问题定义", literature_reading: "文献阅读", paper_understanding: "论文理解", evidence_organization: "证据整理", conclusion_formation: "形成结论" };
export function usePaperCenter() {
  const route = useRoute(); const router = useRouter(); const data = shallowRef<PaperCenterData | null>(null); const loading = shallowRef(false); const error = shallowRef<string | null>(null); const actionMessage = shallowRef(""); const query = shallowRef(typeof route.query.q === "string" ? route.query.q : ""); let requestId = 0; let timer: ReturnType<typeof setTimeout> | undefined;
  const filteredTasks = computed(() => { const q = query.value.trim().toLowerCase(); if (!q || !data.value) return data.value?.continue_tasks ?? []; return data.value.continue_tasks.filter((task) => [task.title, task.journal, task.current_section].some((value) => value?.toLowerCase().includes(q))); });
  async function load(): Promise<void> { const id = ++requestId; loading.value = true; error.value = null; try { const result = await paperResearchCenterApi.center(); if (id === requestId) data.value = result; } catch (cause) { if (id === requestId) error.value = cause instanceof Error ? cause.message : "论文中心加载失败"; } finally { if (id === requestId) loading.value = false; } }
  function updateQuery(value: string): void { query.value = value; if (timer) clearTimeout(timer); timer = setTimeout(() => { void router.replace({ query: { ...route.query, q: value || undefined } }); }, 180); }
  function targetPath(task: CenterTask): string | null { const target = task.next_action.target; if (!task.entry_available || !task.next_action.is_available || !target) return null; const params = new URLSearchParams(); if (target.session_id !== undefined && target.session_id !== null) params.set("session_id", String(target.session_id)); if (target.page !== undefined && target.page !== null) params.set("page", String(target.page)); if (target.offset !== undefined && target.offset !== null) params.set("offset", String(target.offset)); return `/paper-research/${String(target.item_id ?? task.paper_item_id)}${params.size ? `?${params.toString()}` : ""}`; }
  async function continueTask(task: CenterTask): Promise<void> { const path = targetPath(task); if (!path) { actionMessage.value = task.next_action.unavailable_reason ?? "此任务暂不可用"; return; } try { await router.push(path); } catch (cause) { actionMessage.value = cause instanceof Error ? cause.message : "无法打开阅读位置，请稍后重试"; } }
  async function openActivityTarget(activity: { target: Record<string, unknown> | null; target_available: boolean; paper_item_id: number }): Promise<void> { if (!activity.target_available) { actionMessage.value = "该研究动态暂不可回跳"; return; } const target = activity.target ?? { item_id: activity.paper_item_id }; const path = `/paper-research/${String(target.item_id ?? activity.paper_item_id)}${target.page !== undefined || target.offset !== undefined ? `?${new URLSearchParams({ ...(target.page !== undefined ? { page: String(target.page) } : {}), ...(target.offset !== undefined ? { offset: String(target.offset) } : {}) })}` : ""}`; try { await router.push(path); } catch (cause) { actionMessage.value = cause instanceof Error ? cause.message : "无法打开研究动态"; } }
  async function addPaper(): Promise<void> { const doi = window.prompt("输入 DOI（或取消）"); if (!doi?.trim()) return; try { await paperLibraryApi.add({ doi: doi.trim() }); actionMessage.value = "论文已添加，正在刷新中心"; await load(); } catch (cause) { actionMessage.value = cause instanceof Error ? cause.message : "添加论文失败"; } }
  watch(() => route.query.q, (value) => { if (typeof value === "string" && value !== query.value) query.value = value; }); onMounted(load);
  return { data, loading, error, actionMessage, query, filteredTasks, stageLabels, load, updateQuery, continueTask, openActivityTarget, addPaper, targetPath };
}
