<script setup lang="ts">
import { computed } from "vue";
import type { StrategyListItem } from "../../api/literatureStrategies";
import StrategyActionMenu from "./StrategyActionMenu.vue";
const props = defineProps<{ item: StrategyListItem; active: boolean }>();
const emit = defineEmits<{ select: [id: number]; rerun: []; action: [action: "rename" | "move" | "clone" | "archive" | "restore", id: number] }>();
const execution = computed(() => props.item.latest_execution);
const frameworkLabel = computed(() => props.item.framework === "topic" ? "主题检索" : props.item.framework);
const executionTime = computed(() => execution.value ? new Intl.DateTimeFormat("zh-CN", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(execution.value.created_at)) : "尚未执行");
</script>
<template>
  <article class="strategy-card history-item" :data-strategy-id="props.item.id" :class="{ active: props.active }" :aria-current="props.active ? 'true' : undefined" tabindex="0" @click="emit('select', props.item.id)" @keydown.enter="emit('select', props.item.id)" @keydown.space.prevent="emit('select', props.item.id)">
    <div class="strategy-copy"><h2>{{ props.item.name }} <small class="version">v{{ props.item.current_version }}</small> <small class="framework">{{ frameworkLabel }}</small></h2><p :title="props.item.original_query">{{ props.item.original_query }}</p><span class="meta">PubMed　·　{{ props.item.keyword_count }} 关键词　·　{{ props.item.mesh_count }} MeSH<span v-if="props.item.start_year">　·　{{ props.item.start_year }} – {{ props.item.end_year }}</span></span></div>
    <div class="result"><small>最近结果</small><strong>{{ execution?.result_count ?? 0 }}</strong><span>篇</span><time>{{ executionTime }}</time></div>
    <div class="actions" @click.stop><button v-if="props.active" class="rerun" type="button" @click="emit('rerun')">再次检索</button><RouterLink v-else class="outline" :to="`/literature-search?strategy=${props.item.id}`">打开策略</RouterLink><RouterLink v-if="execution?.result_id" class="outline" :to="`/literature-search/results/${execution.result_id}?from=history`">查看结果</RouterLink><StrategyActionMenu :strategy-id="props.item.id" :archived="props.item.is_archived" @action="(action, id) => emit('action', action, id)" /></div>
  </article>
</template>
<style scoped>
.strategy-card { display:grid; grid-template-columns:minmax(0,1fr) 76px auto; gap:12px; align-items:center; min-height:124px; padding:13px 14px; border:1px solid var(--border-subtle); border-radius:8px; background:var(--surface); cursor:pointer; }.strategy-card:hover { border-color:#bfd3f7; box-shadow:0 3px 12px rgb(20 45 90 / 6%); }.strategy-card:focus-visible { outline:2px solid var(--color-primary); outline-offset:2px; }.strategy-card.active { border-color:#9cc4ff; background:#f6f9ff; }.strategy-copy { min-width:0; }.strategy-copy h2,.strategy-copy p { overflow:hidden; white-space:nowrap; text-overflow:ellipsis; }.strategy-copy h2 { margin:0; color:var(--text-primary); font-size:14px; line-height:20px; }.strategy-copy small { display:inline-block; margin-left:6px; padding:2px 5px; border-radius:4px; font-size:10px; font-weight:700; vertical-align:1px; }.version { background:#e8f8f1; color:#079669; }.framework { background:#eaf3ff; color:var(--color-primary); }.strategy-copy p { margin:8px 0; color:var(--text-secondary); font-size:12px; }.meta,.result small,.result time { color:var(--text-muted); font-size:11px; }.result { display:grid; grid-template-columns:auto auto; column-gap:2px; align-items:baseline; text-align:right; }.result small,.result time { grid-column:1 / -1; }.result strong { color:#079669; font-size:18px; font-variant-numeric:tabular-nums; }.result span { color:#079669; font-size:11px; }.actions { display:flex; align-items:center; gap:8px; }.rerun,.outline { min-height:31px; border-radius:6px; padding:0 11px; font:700 11px/1 inherit; text-decoration:none; white-space:nowrap; cursor:pointer; }.rerun { border:1px solid var(--color-primary); background:var(--color-primary); color:#fff; }.outline { border:1px solid var(--border-subtle); background:var(--surface); color:var(--text-primary); }@media (max-width:980px) { .strategy-card { grid-template-columns:minmax(0,1fr) 68px; }.actions { grid-column:1 / -1; justify-content:flex-end; } }
</style>
