<script setup lang="ts">
import { ref } from "vue";
import { conversationsApi,type Citation,type Conversation } from "../../api/conversations";
const ids=ref("");const question=ref("");const conversation=ref<Conversation|null>(null);const selected=ref<Citation|null>(null);const error=ref("");
async function start(){conversation.value=await conversationsApi.create(ids.value.split(",").map(Number).filter(Boolean))}
async function ask(){if(!conversation.value)return;try{const message=await conversationsApi.ask(conversation.value.id,question.value);conversation.value.messages.push({id:Date.now(),role:"user",content:question.value,citations:[]},message);question.value=""}catch(e){error.value=e instanceof Error?e.message:"问答失败"}}
async function rate(messageId:number,rating:number){if(!conversation.value)return;const updated=await conversationsApi.feedback(conversation.value.id,messageId,rating);const index=conversation.value.messages.findIndex(item=>item.id===messageId);if(index>=0)conversation.value.messages[index]=updated}
</script>
<template><main class="chat"><header><p>GROUNDED PAPER CHAT</p><h1>带原文证据的论文问答</h1></header><form v-if="!conversation" @submit.prevent="start"><label>文档 ID（逗号分隔）<input v-model="ids" required /></label><button>创建会话</button></form><template v-else><section class="messages"><article v-for="message in conversation.messages" :key="message.id" :class="message.role"><b>{{message.role==='user'?'你':'论文助手'}}</b><span v-if="message.answer_status==='insufficient_evidence'" class="uncertain">证据不足，不是系统故障</span><span v-if="message.answer_status==='failed'" class="failed">系统失败</span><p>{{message.content}}</p><button v-for="citation in message.citations" :key="citation.id" class="citation" @click="selected=citation">文档 {{citation.document_id}}<template v-if="citation.page"> · 第 {{citation.page}} 页</template></button><span v-if="message.role==='assistant'"><button aria-label="回答有帮助" @click="rate(message.id,1)">有帮助</button><button aria-label="回答需改进" @click="rate(message.id,-1)">需改进</button></span></article></section><form @submit.prevent="ask"><input v-model="question" maxlength="4000" required placeholder="询问研究方法、数字或结论"/><button>提问</button></form></template><p role="alert">{{error}}</p><aside v-if="selected"><button @click="selected=null">关闭</button><h2>原文证据</h2><p>{{selected.citation_text||'来源未提供题录'}}</p><blockquote>{{selected.evidence_text||'来源未返回证据摘录'}}</blockquote></aside></main></template>
<style scoped>.chat{max-width:900px;margin:auto;padding:4rem 1rem}h1{font:700 3rem Georgia,serif;color:#173f3c}form{display:flex;gap:.6rem;padding:1rem;background:white;border-radius:14px}label{flex:1}input{width:100%;padding:.7rem;border:1px solid #9cafaa;border-radius:8px}button{border:0;border-radius:8px;padding:.6rem .85rem;background:#173f3c;color:white}.messages{display:grid;gap:.8rem;margin:1rem 0}.messages article{padding:1rem;background:white;border-radius:14px}.messages .user{margin-left:20%;background:#e5eee9}.citation{margin-right:.4rem;background:#a94d2d}.uncertain,.failed{margin-left:.6rem;padding:.2rem .45rem;border-radius:99px;background:#fff0d2;font-size:.75rem}.failed{background:#f4e5e2}aside{position:fixed;right:1rem;top:5rem;width:min(360px,85vw);padding:1.2rem;background:#fff8e9;box-shadow:0 12px 40px #173f3c33;border-radius:14px}blockquote{border-left:3px solid #d8a347;padding-left:1rem}</style>
