<script setup lang="ts">
import { computed, onMounted, shallowRef } from "vue";
import { conversationsApi, type Citation, type Conversation, type ConversationSummary } from "../../api/conversations";
import EvidencePanel from "../../components/evidence/EvidencePanel.vue";
import type { EvidenceItemModel } from "../../components/evidence/EvidenceItem.vue";
import ExportButton from "../../components/common/ExportButton.vue";
const documentIds = shallowRef(""); const question = shallowRef(""); const conversation = shallowRef<Conversation | null>(null); const history = shallowRef<ConversationSummary[]>([]); const selected = shallowRef<EvidenceItemModel | null>(null); const error = shallowRef<string | null>(null); const loading = shallowRef(false);
const evidence = computed<EvidenceItemModel[]>(() => conversation.value?.messages.flatMap(message => message.citations.map(citation => ({ id: citation.id, title: citation.citation_text, excerpt: citation.evidence_text, page: citation.page, section: citation.section, kind: "paper" }))) ?? []);
async function loadHistory() { try { history.value = await conversationsApi.list(); } catch { error.value = "会话列表暂不可用"; } }
async function start() { loading.value = true; error.value = null; try { conversation.value = await conversationsApi.create(documentIds.value.split(",").map(Number).filter(Boolean)); } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法创建会话"; } finally { loading.value = false; } }
async function restore(id: number) { conversation.value = await conversationsApi.get(id); }
async function ask() { if (!conversation.value || !question.value.trim()) return; loading.value = true; error.value = null; try { const userText = question.value; question.value = ""; const answer = await conversationsApi.ask(conversation.value.id, userText); conversation.value = { ...conversation.value, messages: [...conversation.value.messages, { id: -Date.now(), role: "user", content: userText, citations: [] }, answer] }; } catch (cause) { error.value = cause instanceof Error ? cause.message : "问答失败"; } finally { loading.value = false; } }
async function rate(messageId: number, rating: number) { if (!conversation.value) return; const updated = await conversationsApi.feedback(conversation.value.id, messageId, rating); conversation.value = { ...conversation.value, messages: conversation.value.messages.map(item => item.id === messageId ? updated : item) }; }
onMounted(loadHistory);
</script>
<template><main class="chat-layout"><nav class="conversation-list"><button class="new" @click="conversation = null">＋ 新建会话</button><p>历史会话</p><button v-for="item in history" :key="item.id" class="history" @click="restore(item.id)">{{ item.title || `会话 ${item.id}` }}<small>{{ item.message_count }} 条消息</small></button></nav><section class="chat"><header><p class="eyebrow">GROUNDED PAPER CHAT · LIVE</p><h1>带原文证据的论文问答</h1><p>回答仅来自已索引文档；证据不足时会明确说明。</p></header><form v-if="!conversation" class="start" @submit.prevent="start"><label>文档范围（ID，逗号分隔）<input v-model="documentIds" required placeholder="例如：12, 18" /></label><button :disabled="loading">创建会话</button></form><template v-else><div class="chat-tools"><span>文档范围：{{ conversation.document_ids.join("、") }}</span><ExportButton type="conversation" :source-id="conversation.id" /></div><article v-for="message in conversation.messages" :key="message.id" :class="['message', message.role]"><b>{{ message.role === 'user' ? '你' : '研究助手' }}</b><p>{{ message.content }}</p><p v-if="message.answer_status === 'insufficient_evidence'" class="notice">证据不足：系统不会把模型推断当作论文事实。</p><div class="citations"><button v-for="citation in message.citations" :key="citation.id" @click="selected = { id: citation.id, title: citation.citation_text, excerpt: citation.evidence_text, page: citation.page, section: citation.section, kind: 'paper' }">引用 · 页码 {{ citation.page ?? "未提供" }}</button></div><div v-if="message.role === 'assistant'" class="feedback"><button @click="rate(message.id, 1)">有帮助</button><button @click="rate(message.id, -1)">引用/数据需修正</button></div></article><form class="ask" @submit.prevent="ask"><input v-model="question" :disabled="loading" required maxlength="4000" placeholder="询问研究方法、数字或结论" /><button :disabled="loading">{{ loading ? "问答中" : "发送" }}</button></form></template><p v-if="error" role="alert" class="error">{{ error }}</p></section><EvidencePanel :items="evidence" @open="selected = $event" /><dialog :open="Boolean(selected)"><button @click="selected = null">关闭</button><h2>{{ selected?.title || "来源未提供" }}</h2><p>页码：{{ selected?.page ?? "未提供" }} · {{ selected?.section || "章节未提供" }}</p><blockquote>{{ selected?.excerpt || "原文摘录未提供" }}</blockquote></dialog></main></template>
<style scoped>.chat-layout{display:grid;grid-template-columns:220px minmax(0,1fr) 290px;min-height:calc(100vh - 72px)}.conversation-list,.chat{padding:1.4rem}.conversation-list{border-right:1px solid var(--border-subtle);background:var(--surface-raised)}.new,.history{display:grid;gap:.3rem;width:100%;margin-bottom:.55rem;padding:.7rem;border:1px solid var(--border-subtle);border-radius:8px;background:var(--paper);text-align:left}.new{background:var(--color-primary);color:#fff;font-weight:800}.history small{color:var(--text-muted)}.eyebrow{color:var(--color-primary);font-size:.72rem;font-weight:900;letter-spacing:.1em}.chat h1{margin:.25rem 0;font-size:2rem}.chat>header>p:last-child{color:var(--text-muted)}.start,.ask{display:flex;gap:.7rem;padding:1rem;border:1px solid var(--border-subtle);border-radius:var(--radius-md);background:var(--paper)}.start label{display:grid;gap:.35rem;flex:1}.start input,.ask input{flex:1;width:100%;padding:.65rem;border:1px solid var(--border-strong);border-radius:8px}.start button,.ask button{border:0;border-radius:8px;padding:.65rem .9rem;background:var(--color-primary);color:#fff}.chat-tools{display:flex;justify-content:space-between;margin:1rem 0;color:var(--text-muted)}.message{margin:1rem 0;padding:1rem;border:1px solid var(--border-subtle);border-radius:var(--radius-md);background:var(--paper)}.message.user{margin-left:10%;background:var(--color-primary-soft)}.citations,.feedback{display:flex;gap:.45rem;flex-wrap:wrap}.citations button,.feedback button{border:0;border-radius:6px;padding:.35rem .55rem;background:var(--surface-muted);color:var(--color-primary)}.notice{padding:.6rem;border-radius:8px;background:var(--color-warning-soft);color:var(--color-warning)}.error{color:var(--color-danger)}dialog{position:fixed;right:1rem;top:5rem;width:min(400px,90vw);border:1px solid var(--border-subtle);border-radius:var(--radius-md);padding:1rem;background:var(--paper)}dialog::backdrop{background:transparent}@media(max-width:950px){.chat-layout{grid-template-columns:180px 1fr}.chat-layout>:last-child{display:none}}@media(max-width:650px){.chat-layout{grid-template-columns:1fr}.conversation-list{border-right:0;border-bottom:1px solid var(--border-subtle)}.conversation-list .history{display:none}}</style>
