<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { useRoute } from "vue-router";
import { writingProjectsApi, type DisclosureDraft, type GeneratedContent, type WritingProject, type WritingVersion } from "../../api/writingProjects";

const route = useRoute(); const project = ref<WritingProject | null>(null); const draft = ref(""); const material = ref(""); const versions = ref<WritingVersion[]>([]); const disclosure = ref<DisclosureDraft | null>(null); const saving = ref(false); const error = ref(""); const projectId = computed(() => Number(route.params.id));
function contentFromDraft(current: GeneratedContent): GeneratedContent { return { ...current, sections: [{ id: "draft", title: "草稿", draft: draft.value }] }; }
async function load(): Promise<void> { try { project.value = await writingProjectsApi.get(projectId.value); draft.value = project.value.generated_content.sections.map((section) => section.draft).join("\n\n"); versions.value = await writingProjectsApi.listVersions(projectId.value); disclosure.value = await writingProjectsApi.getDisclosure(projectId.value); } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法读取写作项目。"; } }
async function save(): Promise<void> { if (!project.value) return; saving.value = true; error.value = ""; try { project.value = await writingProjectsApi.updateContent(project.value, contentFromDraft(project.value.generated_content)); } catch (cause) { error.value = cause instanceof Error ? cause.message : "保存失败；如有版本冲突，请重新打开项目。"; } finally { saving.value = false; } }
async function addMaterial(): Promise<void> { if (!project.value || !material.value.trim()) return; saving.value = true; try { await writingProjectsApi.addMaterial(project.value.id, material.value.trim()); material.value = ""; project.value = await writingProjectsApi.get(project.value.id); } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法添加材料。"; } finally { saving.value = false; } }
async function snapshot(): Promise<void> { if (!project.value) return; await save(); if (!project.value) return; try { await writingProjectsApi.saveVersion(project.value); versions.value = await writingProjectsApi.listVersions(project.value.id); } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法保存版本快照。"; } }
async function restore(version: WritingVersion): Promise<void> { if (!project.value) return; saving.value = true; try { project.value = await writingProjectsApi.restoreVersion(project.value, version.version); draft.value = project.value.generated_content.sections.map((section) => section.draft).join("\n\n"); versions.value = await writingProjectsApi.listVersions(project.value.id); } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法恢复该版本。"; } finally { saving.value = false; } }
async function confirmOutline(): Promise<void> { if (!project.value) return; await save(); if (!project.value) return; saving.value = true; try { project.value = await writingProjectsApi.submitOutline(project.value, true); versions.value = await writingProjectsApi.listVersions(project.value.id); } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法提交大纲；请确认当前工作流状态。"; } finally { saving.value = false; } }
async function saveDisclosure(): Promise<void> { if (!disclosure.value) return; try { disclosure.value = await writingProjectsApi.updateDisclosure(disclosure.value.id, disclosure.value.content); } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法保存 AI 使用披露。"; } }
onMounted(() => void load());
</script>
<template><main class="editor"><header><div><p class="eyebrow">WRITING EDITOR · LIVE</p><h1>{{ project?.name ?? "写作项目" }}</h1><p>版本 {{ project?.version ?? "-" }} · 工作流：{{ project?.generated_content.workflow_state ?? "-" }}</p></div><div class="actions"><button :disabled="saving || !project" @click="save">保存草稿</button><button :disabled="saving || !project" @click="snapshot">保存快照</button><button :disabled="saving || !project" @click="confirmOutline">确认大纲</button></div></header><p v-if="error" class="error">{{ error }}</p><textarea v-if="project" v-model="draft" aria-label="写作草稿" placeholder="在此撰写或编辑草稿。"></textarea><p v-else-if="!error" class="loading">正在读取项目…</p><section v-if="project" class="panels"><article><h2>用户材料</h2><form @submit.prevent="addMaterial"><textarea v-model="material" maxlength="20000" placeholder="粘贴由用户提供的材料；不会自动视为文献证据。"></textarea><button :disabled="saving || !material.trim()">添加材料</button></form><ul><li v-for="item in project.user_materials" :key="item.id">{{ item.text }}</li><li v-if="!project.user_materials.length">尚无材料</li></ul></article><article><h2>版本快照</h2><ul><li v-for="version in versions" :key="version.version">v{{ version.version }} <button :disabled="saving" @click="restore(version)">恢复</button></li><li v-if="!versions.length">尚无快照</li></ul></article><article v-if="disclosure"><h2>AI 使用披露</h2><textarea v-model="disclosure.content" aria-label="AI 使用披露"></textarea><button @click="saveDisclosure">保存披露文本</button></article></section></main></template>
<style scoped>.editor{padding:1.5rem;max-width:1200px}.editor header{display:flex;justify-content:space-between;gap:1rem;align-items:start}.eyebrow{margin:0;color:var(--color-primary);font-size:.72rem;font-weight:900;letter-spacing:.12em}h1{margin:.25rem 0}header p{color:var(--text-muted)}button{border:0;border-radius:7px;padding:.5rem .7rem;background:var(--color-primary);color:#fff;font:inherit;font-weight:750;cursor:pointer}.actions{display:flex;gap:.45rem;flex-wrap:wrap}.editor>textarea{box-sizing:border-box;width:100%;min-height:420px;margin-top:1rem;padding:1rem;border:1px solid var(--border-subtle);border-radius:7px;font:inherit;line-height:1.65;resize:vertical}.error{padding:.7rem;background:var(--color-danger-soft);color:var(--color-danger);border-radius:7px}.loading{color:var(--text-muted)}.panels{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.9rem;margin-top:1rem}.panels article{padding:1rem;border:1px solid var(--border-subtle);border-radius:7px;background:var(--paper)}.panels h2{margin:0 0 .6rem;font-size:1rem}.panels textarea{box-sizing:border-box;width:100%;min-height:100px;margin-bottom:.5rem;padding:.6rem;border:1px solid var(--border-subtle);border-radius:6px;font:inherit}.panels ul{padding-left:1.1rem;line-height:1.5}.panels li{margin:.35rem 0}@media(max-width:800px){.editor header{display:block}.actions{margin-top:.7rem}.panels{grid-template-columns:1fr}}</style>
