<script setup lang="ts">
import { shallowRef } from "vue";
const activeSection = shallowRef("提纲"); const draft = shallowRef("");
const sections = ["提纲", "引言草稿", "讨论草稿", "材料与版本"];
</script>

<template><main class="editor"><header class="editor-header"><div><p class="eyebrow">WRITING EDITOR · MOCK</p><h1>本地写作草稿</h1><p>版本：本地 v0 · 未与后端同步</p></div><div><button>润色（未接入）</button><button class="primary">保存本地草稿</button></div></header><div class="editor-grid"><aside class="left"><p class="eyebrow">SECTIONS</p><button v-for="section in sections" :key="section" :class="{ active: section === activeSection }" @click="activeSection = section">{{ section }}</button><hr><small>材料：未接入</small><small>版本时间线：本地原型</small></aside><section class="canvas"><p class="eyebrow">{{ activeSection }}</p><div class="origin-bar">段落来源：用户 · 模型总结、模型推断与待确认将单独标记</div><textarea v-model="draft" aria-label="写作草稿" placeholder="在此记录用户草稿；本原型不会自动生成医学论文内容。"></textarea><div class="selection-actions"><button>标记来源</button><button>待确认</button><button>润色（未接入）</button></div></section><aside class="right"><p class="eyebrow">CITATION CHECK · MOCK</p><h2>引用与核验</h2><p>DOI/PMID：未接入</p><p>原文证据：未接入</p><p>引用核验：待接入</p><hr><p class="eyebrow">AI USAGE</p><p>AI 使用记录：未接入；不能声明已由 AI 生成。</p></aside></div></main></template>

<style scoped>.editor{min-height:calc(100vh - 65px)}.editor-header{display:flex;justify-content:space-between;gap:1rem;padding:1.25rem 1.4rem;border-bottom:1px solid var(--border-subtle);background:var(--paper)}.eyebrow{margin:0;color:var(--color-primary);font-size:.72rem;font-weight:900;letter-spacing:.12em}.editor-header h1{margin:.25rem 0;font-size:1.65rem}.editor-header p:last-child,.right p{color:var(--text-muted)}button{border:1px solid var(--border-strong);border-radius:6px;padding:.45rem .6rem;background:var(--paper);font-weight:700}.primary{border-color:var(--color-primary);background:var(--color-primary);color:#fff}.editor-grid{display:grid;grid-template-columns:210px minmax(0,1fr) 280px;min-height:calc(100vh - 150px)}.left,.right{padding:1.1rem;background:var(--surface-raised)}.left{border-right:1px solid var(--border-subtle)}.left button{display:block;width:100%;margin:.3rem 0;border:0;background:transparent;text-align:left}.left button.active{border-left:3px solid var(--color-primary);background:var(--surface-muted);color:var(--color-primary)}.left small{display:block;margin:.6rem 0;color:var(--text-muted)}.canvas{padding:1.4rem}.origin-bar{padding:.6rem .75rem;background:var(--surface-muted);color:var(--text-muted);font-size:.86rem}.canvas textarea{width:100%;min-height:420px;margin-top:.8rem;padding:1rem;border:1px solid var(--border-subtle);border-radius:6px;background:var(--paper);font:inherit;line-height:1.65;resize:vertical}.selection-actions{display:flex;gap:.5rem;margin-top:.7rem}.right{border-left:1px solid var(--border-subtle)}.right h2{margin:.25rem 0}@media(max-width:980px){.editor-grid{grid-template-columns:180px minmax(0,1fr)}.right{display:none}}@media(max-width:720px){.editor-header{display:block}.editor-header>div:last-child{margin-top:.7rem}.editor-grid{grid-template-columns:1fr}.left{border-right:0;border-bottom:1px solid var(--border-subtle)}.left button{display:inline-block;width:auto}.canvas{padding:1rem}}</style>
