<script setup lang="ts">
import { onMounted, ref } from "vue";
import { useRouter } from "vue-router";
import { writingProjectsApi, type WritingProject, type WritingType } from "../../api/writingProjects";
const router = useRouter(); const projects = ref<WritingProject[]>([]); const name = ref(""); const writingType = ref<WritingType>("review"); const error = ref(""); const saving = ref(false);
async function load(): Promise<void> { try { projects.value = await writingProjectsApi.list(); } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法读取写作项目。"; } }
async function create(): Promise<void> { if (!name.value.trim()) return; saving.value = true; error.value = ""; try { const project = await writingProjectsApi.create(name.value.trim(), writingType.value); await router.push(`/writing/${project.id}`); } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法创建写作项目。"; } finally { saving.value = false; } }
onMounted(() => void load());
</script>
<template><main class="page"><header><p class="eyebrow">WRITING PROJECTS · LIVE</p><h1>写作辅助</h1><p>项目、草稿和版本由后端保存。此页面不生成或伪造文献证据。</p></header><form class="create" @submit.prevent="create"><input v-model.trim="name" maxlength="200" placeholder="项目名称"><select v-model="writingType"><option value="review">综述</option><option value="proposal">开题</option><option value="reading_note">读书笔记</option><option value="group_meeting">组会</option><option value="introduction">引言</option><option value="discussion">讨论</option><option value="abstract">摘要</option></select><button :disabled="saving || !name">新建项目</button></form><p v-if="error" class="error">{{ error }}</p><section class="grid"><article v-for="project in projects" :key="project.id"><p class="eyebrow">{{ project.writing_type }} · v{{ project.version }}</p><h2>{{ project.name }}</h2><p>最近更新：{{ new Date(project.updated_at).toLocaleString() }}</p><button @click="router.push(`/writing/${project.id}`)">打开草稿</button></article><p v-if="!projects.length" class="empty">尚无写作项目。</p></section></main></template>
<style scoped>.page{padding:2rem 1.4rem;max-width:1200px}.eyebrow{margin:0;color:var(--color-primary);font-size:.72rem;font-weight:900;letter-spacing:.12em}h1{margin:.25rem 0;font-size:2.3rem}header>p:last-child,article>p:not(.eyebrow){color:var(--text-muted)}.create{display:flex;gap:.6rem;margin:1.2rem 0}.create input,.create select{min-width:0;padding:.6rem;border:1px solid var(--border-subtle);border-radius:7px;background:var(--paper);font:inherit}.create input{flex:1}.create button,article button{border:0;border-radius:7px;padding:.6rem .8rem;background:var(--color-primary);color:#fff;font:inherit;font-weight:750}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.9rem}.grid article,.empty{padding:1rem;border:1px solid var(--border-subtle);border-radius:var(--radius-md);background:var(--paper)}.grid h2{margin:.4rem 0}.error{padding:.7rem;background:var(--color-danger-soft);color:var(--color-danger);border-radius:7px}@media(max-width:720px){.create{display:grid}.grid{grid-template-columns:1fr}}</style>
