import { flushPromises, mount } from "@vue/test-utils";
import { createMemoryHistory, createRouter } from "vue-router";
import { afterEach, expect, test, vi } from "vitest";
import PaperAnalysisView from "./PaperAnalysisView.vue";

const indexed = { items: [{ document_id: 42, title: "Indexed trial.pdf", year: 2024, pmid: "12345" }], total: 1, offset: 0, limit: 10 };
const emptyOverview = { recent_analyses: [], pending_confirmations: [], recent_conversations: [] };
function response(body: unknown, status = 200): Response { return new Response(JSON.stringify(body), { status, headers: { "Content-Type": "application/json" } }); }
async function mountPage(path = "/analysis") { const router = createRouter({ history: createMemoryHistory(), routes: [{ path: "/analysis", component: PaperAnalysisView }, { path: "/chat", component: { template: "<p>chat</p>" } }] }); await router.push(path); await router.isReady(); return { router, wrapper: mount(PaperAnalysisView, { global: { plugins: [router] } }) }; }
afterEach(() => vi.restoreAllMocks());

test("loads real indexed and overview APIs and has no document ID input", async () => {
  const fetchMock = vi.fn((input: RequestInfo | URL) => Promise.resolve(response(String(input).includes("indexed-documents") ? indexed : emptyOverview)));
  vi.stubGlobal("fetch", fetchMock); const { wrapper } = await mountPage(); await flushPromises();
  expect(wrapper.get("h1").text()).toBe("论文研究"); expect(wrapper.text()).toContain("研究概览"); expect(wrapper.text()).toContain("Indexed trial.pdf"); expect(wrapper.find('input[type="number"]').exists()).toBe(false);
  expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining("/api/v1/paper-research/indexed-documents"), undefined);
});
test("shows actionable API failure without mock fallback", async () => { vi.stubGlobal("fetch", vi.fn(() => Promise.resolve(response({ detail: "overview unavailable" }, 500)))); const { wrapper } = await mountPage(); await flushPromises(); expect(wrapper.text()).toContain("overview unavailable"); expect(wrapper.text()).not.toContain("Indexed trial.pdf"); });
test("selecting an indexed paper carries its real ID into single-paper reading", async () => { vi.stubGlobal("fetch", vi.fn((input: RequestInfo | URL) => { const url = String(input); if (url.includes("indexed-documents")) return Promise.resolve(response(indexed)); if (url.includes("/documents?")) return Promise.resolve(response({ items: [], total: 0, offset: 0, limit: 10 })); if (url.endsWith("/documents/42")) return Promise.resolve(response({ detail: "not found" }, 404)); return Promise.resolve(response(emptyOverview)); })); const { router, wrapper } = await mountPage(); await flushPromises(); await wrapper.get(".paper-list button").trigger("click"); await flushPromises(); expect(router.currentRoute.value.query).toMatchObject({ documentId: "42", tab: "reading" }); });

test("evidence URL restores the selected document and its latest conversation in place", async () => { const activeDocument = { id: 42, original_filename: "live-paper.pdf", file_path: "papers/live.pdf", parse_status: "succeeded", index_status: "succeeded", paperqa_index_key: "index-42", knowledge_source_id: 1, media_type: "application/pdf", file_hash: "hash", file_size: 1, modified_time: "2026-01-01", scan_state: "pending", error_code: null, error_message: null, retry_count: 0, started_at: null, finished_at: null, parsed_is_scanned: false }; const fetchMock = vi.fn((input: RequestInfo | URL) => { const url = String(input); if (url.endsWith("/documents/42")) return Promise.resolve(response(activeDocument)); if (url.includes("/conversations/latest?document_id=42")) return Promise.resolve(response({ id: 5, document_ids: [42], title: null, research_context_id: null, messages: [] })); if (url.includes("/conversations")) return Promise.resolve(response([])); if (url.includes("/documents?")) return Promise.resolve(response({ items: [], total: 0, offset: 0, limit: 10 })); return Promise.resolve(response(emptyOverview)); }); vi.stubGlobal("fetch", fetchMock); const { wrapper } = await mountPage("/analysis?documentId=42&tab=evidence"); await flushPromises(); expect(wrapper.text()).toContain("live-paper.pdf"); expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining("/conversations/latest?document_id=42"), undefined); expect(wrapper.find(".evidence-workspace").exists()).toBe(true); });
