<script setup lang="ts">
import { nextTick,ref,watch } from "vue";import { recommendationApi,type RecommendationRun } from "../../api/recommendations";
const props=defineProps<{open:boolean;resultId:number|null;returnFocus:HTMLElement|null}>();const emit=defineEmits<{close:[]}>();const runs=ref<RecommendationRun[]>([]);const loading=ref(false);const error=ref<string|null>(null);const panel=ref<HTMLElement|null>(null);
const modeLabel=(mode:string)=>mode==='balanced'?'综合推荐':mode==='latest'?'关注最新':'关键证据';const statusLabel=(status:string)=>({queued:'等待中',running:'生成中',active:'当前版本',failed:'失败',cancelled:'已取消',superseded:'已替代'}[status]||status);const date=(v:string)=>new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v));
async function load(){if(!props.resultId)return;loading.value=true;error.value=null;try{runs.value=await recommendationApi.listRuns(props.resultId)}catch(e){error.value=e instanceof Error?e.message:"推荐历史读取失败"}finally{loading.value=false}}function close(){emit('close')}function keydown(e:KeyboardEvent){if(e.key==='Escape'){close();return}if(e.key==='Tab'&&panel.value){const nodes=[...panel.value.querySelectorAll<HTMLElement>('button,[href],[tabindex]:not([tabindex="-1"])')];if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
watch(()=>props.open,async open=>{if(open){await load();await nextTick();panel.value?.focus()}else props.returnFocus?.focus()});
</script>
<template><div v-if="open" class="backdrop" @click.self="close"><aside ref="panel" class="drawer" role="dialog" aria-modal="true" aria-labelledby="history-title" tabindex="-1" @keydown="keydown"><header><div><p>Recommendation Runs</p><h2 id="history-title">推荐历史</h2></div><button type="button" aria-label="关闭推荐历史" @click="close">×</button></header><p v-if="loading" role="status">正在读取推荐历史…</p><div v-else-if="error" role="alert"><p>{{ error }}</p><button type="button" @click="load">重试</button></div><p v-else-if="!runs.length">当前检索尚无推荐历史。</p><ol v-else><li v-for="run in runs" :key="run.run_id"><div><strong>{{ modeLabel(run.mode) }}</strong><span :class="run.status">{{ statusLabel(run.status) }}</span></div><p>{{ date(run.created_at) }} · {{ run.candidate_count }}篇候选</p><p>完成 {{ run.completed_count }}/{{ run.expected_count }}<template v-if="run.covered_count"> · 已覆盖 {{ run.covered_count }}</template></p><p v-if="run.last_error" class="error">{{ run.last_error.message }}</p><p v-for="warning in run.warnings" :key="warning" class="warning">{{ warning }}</p></li></ol></aside></div></template>
<style scoped>.backdrop{position:fixed;z-index:45;inset:0;background:rgb(15 30 60/.28)}.drawer{position:absolute;z-index:50;top:0;right:0;width:min(460px,100%);height:100%;box-sizing:border-box;overflow:auto;padding:20px 24px;background:#fbfcfe;box-shadow:-8px 0 24px rgb(15 23 42/.08);outline:none}.drawer>header{display:flex;justify-content:space-between;padding-bottom:14px;border-bottom:1px solid #e2e8f0}.drawer header p{margin:0;color:#0b5fcc;font-size:12px}.drawer h2{margin:3px 0 0;font-size:20px}.drawer header button{width:40px;height:40px;border:1px solid #dce5f0;border-radius:8px;background:#fff;font-size:22px}.drawer ol{margin:0;padding:0;list-style:none}.drawer li{padding:14px 0;border-bottom:1px solid #e2e8f0}.drawer li>div{display:flex;justify-content:space-between}.drawer li span{padding:2px 7px;border-radius:4px;background:#eef2f7;color:#475569;font-size:11px}.drawer li span.active{background:#e8f7ef;color:#087a55}.drawer li span.failed{background:#fff0ef;color:#b42318}.drawer li p{margin:4px 0;color:#64748b;font-size:12px}.drawer .error{color:#b42318}.drawer .warning{color:#8a5700}</style>
