<script setup lang="ts">
import { nextTick, ref, watch } from "vue";import { recommendationApi,type RecommendationItem,type RecommendationReason } from "../../api/recommendations";
const props=defineProps<{open:boolean;resultId:number|null;runId:number|null;pmid:string|null;returnFocus:HTMLElement|null}>();const emit=defineEmits<{close:[]}>();const data=ref<RecommendationItem|null>(null);const loading=ref(false);const error=ref<string|null>(null);const panel=ref<HTMLElement|null>(null);const matchText=(item:RecommendationReason['matches'][number])=>item.status==='matched'&&item.matched_terms.length?`命中：${item.matched_terms.join('、')}`:'未找到明确匹配证据';const sourceText=(source:string)=>source.split(",").map(value=>({pubmed_title:"PubMed 题名",pubmed_abstract_results:"PubMed 摘要",pubmed_mesh:"MeSH 主题词",pubmed_publication_type:"PubMed 文献类型",pubmed_publication_types:"PubMed 文献类型",exploration_query:"实际检索式",intent_snapshot:"已确认研究意图",openalex:"OpenAlex"}[value]??value)).join("、");const limitationText=(item:{code:string;message:string})=>item.code.startsWith('llm_narration_')?'模型表述未通过证据边界校验，已保留可核验的结构化理由':item.message;
async function load(){if(!props.resultId||!props.runId||!props.pmid)return;loading.value=true;error.value=null;try{data.value=await recommendationApi.getExplanation(props.resultId,props.runId,props.pmid)}catch(e){error.value=e instanceof Error?e.message:"完整依据读取失败"}finally{loading.value=false}}
function close(){emit("close")}function keydown(e:KeyboardEvent){if(e.key==="Escape")close();if(e.key==="Tab"&&panel.value){const nodes=[...panel.value.querySelectorAll<HTMLElement>('button,[href],[tabindex]:not([tabindex="-1"])')];if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
watch(()=>props.open,async open=>{if(open){data.value=null;await load();await nextTick();panel.value?.focus()}else props.returnFocus?.focus()});
</script>
<template><div v-if="open" class="backdrop" @click.self="close"><aside ref="panel" class="drawer" role="dialog" aria-modal="true" aria-labelledby="explanation-title" tabindex="-1" @keydown="keydown"><header><div><p>推荐依据</p><h2 id="explanation-title">完整推荐依据</h2></div><button type="button" aria-label="关闭完整依据" @click="close">×</button></header><div v-if="loading" class="state" role="status">正在读取持久化依据…</div><div v-else-if="error" class="state error" role="alert"><p>{{ error }}</p><button type="button" @click="load">重试</button></div><div v-else-if="data" class="content"><section><h3>推荐概述</h3><strong>{{ data.reason.headline }}</strong><p>{{ data.reason.narrative }}</p></section><section><h3>主题匹配证据</h3><article v-for="match in data.reason.matches" :key="`${match.dimension}-${match.reason}`"><b>{{ match.dimension }}</b><p>{{ matchText(match) }}</p><blockquote v-if="match.excerpt">{{ match.excerpt }}</blockquote><small>{{ match.matched_terms.join('、') || '未提供匹配词' }} · {{ sourceText(match.field) }}</small></article><p v-if="!data.reason.matches.length">匹配依据暂不完整</p></section><section><h3>增量价值</h3><p>{{ data.reason.incremental_value || "依据暂不完整" }}</p></section><section><h3>证据来源</h3><p>{{ data.reason.evidence_sources.map(sourceText).join('、') || "依据暂不完整" }}</p></section><section><h3>评分组件可用性</h3><dl><div><dt>相关度</dt><dd>{{ data.relevance_score===null?'数据不足':'已计算' }}</dd></div><div><dt>增量价值</dt><dd>{{ data.incremental_value_score===null?'数据不足':'已计算' }}</dd></div><div><dt>证据适配</dt><dd>{{ data.evidence_fit_score===null?'数据不足':'已计算' }}</dd></div><div><dt>新近性</dt><dd>{{ data.recency_score===null?'数据不足':'已计算' }}</dd></div></dl></section><section v-if="data.reason.limitations.length"><h3>限制与数据缺失</h3><p v-for="limit in data.reason.limitations" :key="limit.code">{{ limitationText(limit) }}</p></section></div></aside></div></template>
<style scoped>.backdrop{position:fixed;z-index:45;inset:0;background:rgb(15 30 60/.28)}.drawer{position:absolute;z-index:50;top:0;right:0;width:min(540px,100%);height:100%;box-sizing:border-box;overflow:auto;padding:20px 24px;background:#fbfcfe;box-shadow:-8px 0 24px rgb(15 23 42/.08);outline:none}.drawer>header{display:flex;justify-content:space-between;padding-bottom:14px;border-bottom:1px solid #e2e8f0}.drawer header p{margin:0;color:#0b5fcc;font-size:12px}.drawer h2{margin:3px 0 0;font-size:20px}.drawer header button{width:40px;height:40px;border:1px solid #dce5f0;border-radius:8px;background:#fff;font-size:22px}.content section{padding:15px 0;border-bottom:1px solid #e2e8f0}.content h3{margin:0 0 7px;font-size:14px}.content p{margin:4px 0;color:#475569;font-size:13px;line-height:1.65}.content article{padding:8px 0}.content small{color:#64748b}.content dl div{display:flex;justify-content:space-between;padding:5px 0}.content dd{margin:0;color:#475569}.state{padding:40px 0;color:#475569}.error{color:#b42318}.error button{min-height:40px}</style>
