<script setup lang="ts">
import type { DocumentNavigationResponse, NavigationCondition } from "../../api/documentNavigation";
defineProps<{ result: DocumentNavigationResponse | null; loading: boolean; error: string | null }>();
const emit = defineEmits<{ retry: [] }>();
function locationLabel(location: DocumentNavigationResponse["results"][number]["location"]): string { return location.page_number ? `第 ${location.page_number} 页` : location.section ? `章节：${location.section}` : "全文摘录"; }
function conditionLabel(condition: NavigationCondition): string { return `${condition.label}：${condition.status === "verified" ? "原文已验证" : "未验证，仅检索相关"}`; }
</script>

<template>
  <section class="results" aria-live="polite"><p v-if="loading" class="status">正在在已解析资料中检索…</p><div v-else-if="error" class="error"><p>{{ error }}</p><button @click="emit('retry')">重试</button></div><template v-else-if="result"><p class="conditions">当前检索条件：{{ result.knowledge_source_id ? "指定知识源" : "全部知识源" }} · 仅已索引文档 · 可检索 {{ result.searchable_document_count }} 篇 · {{ result.strategy === "hybrid" ? "混合检索" : "BM25 检索" }}</p><p v-if="result.fallback_reason" class="status">{{ result.fallback_reason }}</p><ul v-if="result.conditions.length" class="condition-list"><li v-for="condition in result.conditions" :key="condition.label">{{ conditionLabel(condition) }}：{{ condition.reason }}</li></ul><p v-if="!result.results.length" class="status">当前范围没有找到相关内容。请调整关键词、知识源或索引状态后再试；若要找某个文件，请使用下方“按文件名查找”。</p><ul v-else class="result-list"><li v-for="item in result.results" :key="item.document_id"><h3>{{ item.title }}</h3><p class="path">{{ item.knowledge_source_name }} / {{ item.relative_path }}</p><p>{{ item.match_reason }} · {{ locationLabel(item.location) }}</p><p v-for="condition in item.condition_status" :key="condition.label" class="condition">{{ conditionLabel(condition) }}</p><p class="excerpt">{{ item.excerpt }}</p><RouterLink :to="`/documents/${item.document_id}`">打开文档详情</RouterLink></li></ul></template></section>
</template>

<style scoped>
.results{display:grid;gap:.7rem}.conditions,.status{margin:0;padding:.65rem .8rem;border-radius:7px;background:var(--surface-muted);color:var(--text-secondary);font-size:.86rem}.condition-list{display:grid;gap:.3rem;margin:0;padding:.6rem 1.1rem;border-left:3px solid #f59e0b;background:#fffbeb;color:#92400e;font-size:.82rem}.error{display:flex;align-items:center;justify-content:space-between;padding:.7rem .8rem;border:1px solid #fecaca;border-radius:7px;color:var(--color-danger)}.error p{margin:0}.error button{border:1px solid currentColor;border-radius:5px;background:#fff;color:inherit;padding:.3rem .55rem}.result-list{display:grid;gap:.65rem;margin:0;padding:0;list-style:none}.result-list li{padding:.9rem 1rem;border:1px solid var(--border-subtle);border-radius:8px;background:#fff}.result-list h3,.result-list p{margin:0}.result-list h3{font-size:1rem}.result-list p{margin-top:.35rem;color:var(--text-secondary);font-size:.86rem}.result-list .path{color:var(--text-muted);font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:.78rem}.result-list .condition{color:#92400e}.result-list .excerpt{color:var(--text-primary);line-height:1.55}.result-list a{display:inline-block;margin-top:.5rem;color:var(--color-primary);font-weight:700}
</style>
