"""阅读事实的冻结策略与输入上限。"""

EXPOSURE_POLICY_VERSION = "reader-exposure-v1"
EXPOSURE_MIN_MILLISECONDS = 2_000
EXPOSURE_MIN_VISIBLE_RATIO = 0.60
EXPOSURE_MAX_BATCH_SIZE = 100
EXPOSURE_MAX_MILLISECONDS = 300_000
EXPOSURE_MAX_EVENT_SPAN_SECONDS = 600
DEFAULT_ACTOR_SCOPE = "local:default"
HISTORY_MAX_LIMIT = 100
RECORD_COUNTING_POLICY_VERSION = "reader-record-v1"
TRANSLATION_CONTRACT_VERSION = "reader-translation-port-v1"

