<script setup lang="ts">
import { ref } from "vue";
import { type AgentTaskType } from "../../api/agent";
import { useAgentRun } from "../../composables/useAgentRun";
const query = ref(""); const taskType = ref<AgentTaskType>("evidence_qa"); const publishRequested = ref(false);
const { run, trace, error, isLoading, execute, decide, cancel } = useAgentRun();
</script>
<template><main class="agent"><header><div><p class="eyebrow">AGENT LAB · LIVE API</p><h1>Agent 实验室</h1><p>任务使用后端已配置的证据适配器；未配置时安全失败，不生成医学结论。</p></div><span class="badge">{{ run?.workflow_status || "待创建" }}</span></header><div class="grid"><section class="canvas"><label>任务输入<textarea v-model="query" placeholder="输入研究任务" /></label><label>任务类型<select v-model="taskType"><option value="evidence_qa">证据问答</option><option value="literature_search">文献检索</option><option value="research_direction">研究方向</option><option value="writing">科研写作</option></select></label><label><input v-model="publishRequested" type="checkbox">拟发布医学科研输出</label><button :disabled="isLoading || query.length < 2" @click="execute(query, taskType, publishRequested)">{{ isLoading ? "创建中…" : "创建任务" }}</button><p v-if="error" class="error">{{ error }}</p><section v-if="run?.workflow_status === 'awaiting_confirmation'" class="approval"><strong>需要人工审批</strong><p>任务：{{ run.approval_payload?.task_type }}；证据：{{ run.approval_payload?.evidence_status }}</p><p v-for="limitation in run.approval_payload?.limitations" :key="limitation">限制：{{ limitation }}</p><button @click="decide('approve')">批准</button><button @click="decide('reject')">拒绝</button><button @click="cancel">取消</button></section></section><aside><p class="eyebrow">运行轨迹</p><p v-if="!run">尚未创建任务</p><p v-else>运行 ID：{{ run.run_id }}</p><ol><li v-for="event in trace" :key="`${event.node}-${event.status}`">{{ event.node }} · {{ event.status }}<small v-if="event.trace_id"> trace: {{ event.trace_id }}</small></li></ol></aside></div></main></template>
<style scoped>.agent{min-height:calc(100vh - 65px)}header{display:flex;justify-content:space-between;padding:1.4rem;border-bottom:1px solid var(--border-subtle);background:var(--paper)}.eyebrow{color:var(--color-primary);font-size:.72rem;font-weight:900;letter-spacing:.12em}.badge{height:max-content;padding:.4rem .6rem;background:var(--color-warning-soft);border-radius:99px}.grid{display:grid;grid-template-columns:minmax(0,1fr) 320px}.canvas,aside{padding:1.4rem}.canvas{display:grid;gap:1rem}.canvas label{display:grid;gap:.35rem;font-weight:700}.canvas textarea,.canvas select{min-height:2.4rem;padding:.6rem;font:inherit}.canvas textarea{min-height:8rem}.canvas button{width:max-content;padding:.55rem .8rem}.approval{padding:1rem;border-left:3px solid var(--color-warning);background:var(--color-warning-soft)}aside{border-left:1px solid var(--border-subtle);background:var(--surface-raised)}small{display:block;color:var(--text-muted)}.error{color:var(--color-danger)}@media(max-width:700px){.grid{grid-template-columns:1fr}aside{border-left:0;border-top:1px solid var(--border-subtle)}}</style>
