<script setup lang="ts">
import type { DocumentRecord } from "../../api/documents";

const props = defineProps<{ documents: readonly DocumentRecord[]; disabled: boolean; selectedIds: readonly number[]; selectedDocumentId: number | null; sourceNames: Readonly<Record<number, string>> }>();
const emit = defineEmits<{ retryParse: [document: DocumentRecord]; retryIndex: [document: DocumentRecord]; deleteIndex: [document: DocumentRecord]; toggleSelect: [documentId: number, selected: boolean]; selectDocument: [document: DocumentRecord] }>();
const labels: Record<string,string>={pending:"等待",parsing:"处理中",indexing:"处理中",succeeded:"成功",failed:"失败",outdated:"索引过期"};
function isSelected(id:number):boolean{return props.selectedIds.includes(id)}
function formatTime(value:string):string{return new Intl.DateTimeFormat("zh-CN",{dateStyle:"medium"}).format(new Date(value))}
</script>
<template><p v-if="documents.length===0" class="empty">当前范围没有文档。</p><div v-else class="table-wrap"><table><thead><tr><th></th><th>文档</th><th>解析状态</th><th>索引状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody><tr v-for="document in documents" :key="document.id" :class="{selected:document.id===selectedDocumentId}" @click="emit('selectDocument',document)"><td><input :checked="isSelected(document.id)" :disabled="disabled" type="checkbox" :aria-label="`选择文档 ${document.id}`" @click.stop @change="emit('toggleSelect',document.id,($event.target as HTMLInputElement).checked)"></td><td><div class="file"><span class="file-icon">{{ document.media_type === 'application/pdf' ? 'PDF' : 'DOC' }}</span><span><RouterLink :to="`/documents/${document.id}`" @click.stop>{{ document.original_filename ?? document.file_path }}</RouterLink><small>{{ sourceNames[document.knowledge_source_id] ?? `来源 #${document.knowledge_source_id}` }}</small><small v-if="document.error_message" style="color:var(--color-danger)">{{ document.error_message }}</small></span></div></td><td><span class="pill" :class="`status-${document.parse_status}`">● {{ labels[document.parse_status] }}</span></td><td><span class="pill" :class="`status-${document.index_status}`">● {{ labels[document.index_status] }}</span></td><td>{{ formatTime(document.modified_time) }}</td><td class="actions" @click.stop><button v-if="document.parse_status==='failed'||document.parse_status==='pending'" :disabled="disabled" @click="emit('retryParse',document)">{{ document.parse_status==='pending' ? '开始解析' : '重试解析' }}</button><button v-if="document.index_status==='failed'||document.index_status==='outdated'" :disabled="disabled||document.parse_status!=='succeeded'" @click="emit('retryIndex',document)">重试索引</button><button v-if="document.index_status==='succeeded'" :disabled="disabled" @click="emit('deleteIndex',document)">删除索引</button><RouterLink :to="`/documents/${document.id}`">详情</RouterLink></td></tr></tbody></table></div></template>
<style scoped>
.table-wrap{overflow:auto}.table-wrap table{width:100%;border-collapse:collapse;min-width:660px}.table-wrap th,.table-wrap td{padding:10px;border-bottom:1px solid var(--border-subtle);text-align:left;font-size:.76rem}.table-wrap th{color:var(--text-muted);background:#fff}.table-wrap tbody tr:hover,.table-wrap tbody tr.selected{background:#fafcff}.file{display:flex;gap:8px;align-items:center}.file-icon{display:grid;width:25px;height:29px;place-items:center;border-radius:5px;background:var(--color-danger-soft);color:var(--color-danger);font-size:.55rem;font-weight:800}.file a{display:block;color:var(--ink-900,#10213d);font-weight:700;text-decoration:none}.file small{display:block;color:var(--text-muted)}.pill{display:inline-flex;gap:4px;padding:3px 7px;border-radius:999px;background:#f1f4f8;color:#6f8097;font-size:.68rem;font-weight:700;white-space:nowrap}.status-succeeded{background:var(--color-success-soft);color:var(--color-success)}.status-failed{background:var(--color-danger-soft);color:var(--color-danger)}.status-parsing,.status-indexing{background:var(--color-primary-soft);color:var(--color-primary)}.status-outdated{background:var(--color-warning-soft);color:var(--color-warning)}.actions{white-space:nowrap}.actions button,.actions a{margin-right:6px;border:0;background:transparent;color:var(--color-primary);font:inherit;font-size:.7rem;font-weight:700;text-decoration:none}.empty{padding:32px;text-align:center;color:var(--text-muted)}
</style>
