<script setup lang="ts">
import type { KnowledgeSource } from "../../api/knowledgeSources";

defineProps<{ sources: readonly KnowledgeSource[]; disabled: boolean }>();
const emit = defineEmits<{ toggle: [source: KnowledgeSource, enabled: boolean]; remove: [source: KnowledgeSource]; sync: [source: KnowledgeSource]; viewDocuments: [source: KnowledgeSource] }>();
const typeLabels = { local_folder: "本地文件夹", obsidian_vault: "Obsidian Vault", temporary_import: "临时导入" } as const;
const statusLabels = { idle: "等待同步", scanning: "同步中", completed: "已同步", completed_with_errors: "同步含错误", unavailable: "不可用" } as const;
function formatTime(value: string | null): string { return value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "尚未同步"; }
</script>

<template>
  <p v-if="sources.length === 0" class="empty-state">当前筛选条件下没有知识来源。</p>
  <ul v-else class="source-list"><li v-for="source in sources" :key="source.id" class="source-row"><div class="source-main"><span class="source-icon" aria-hidden="true">▰</span><div><h3>{{ source.name }}</h3><p class="source-path">{{ source.root_path }}</p><span class="type-pill">{{ typeLabels[source.source_type] }}</span></div></div><div class="statistics"><span><b>{{ source.stats.total_files }}</b> 个文件</span><span><b>{{ source.stats.indexed }}</b> 已索引</span><span><b>{{ source.stats.pending }}</b> 待处理</span><span :class="{ failed: source.stats.failed > 0 }"><b>{{ source.stats.failed }}</b> 异常</span></div><div class="source-status"><span>上次同步：{{ formatTime(source.last_sync_time) }}</span><strong :class="`status-${source.sync_status}`">● {{ statusLabels[source.sync_status] }}</strong><em v-if="source.error_message" role="alert">{{ source.error_message }}</em></div><div class="source-actions"><button type="button" :disabled="disabled || source.sync_status === 'scanning' || !source.enabled" @click="emit('sync', source)">{{ source.sync_status === 'scanning' ? '同步中' : '同步' }}</button><label class="switch"><input type="checkbox" :checked="source.enabled" :disabled="disabled" @change="emit('toggle', source, ($event.target as HTMLInputElement).checked)"><span></span><i class="sr-only">{{ source.enabled ? '已启用' : '已停用' }}</i></label><button class="document-link" type="button" @click="emit('viewDocuments', source)">查看文档 →</button><button class="remove-action" type="button" :disabled="disabled" @click="emit('remove', source)">⋮</button></div></li></ul>
</template>

<style scoped>
.source-list{margin:0 -26px;padding:0;list-style:none;border-top:1px solid var(--border-subtle)}.source-row{display:grid;grid-template-columns:minmax(250px,1.25fr) minmax(255px,1fr) minmax(155px,.7fr) auto;gap:18px;align-items:center;padding:18px 26px}.source-row+.source-row{border-top:1px solid var(--border-subtle)}.source-row:hover{background:#fafcff}.source-main{display:flex;gap:12px}.source-icon{display:grid;flex:0 0 36px;width:36px;height:36px;place-items:center;border-radius:9px;background:var(--color-primary-soft);color:var(--color-primary)}.source-main h3{margin:0;color:var(--ink-900,#10213d);font-size:.94rem}.source-path{margin:2px 0;color:var(--text-muted);font-family:ui-monospace,Consolas,monospace;font-size:.75rem;overflow-wrap:anywhere}.type-pill{display:inline-block;padding:2px 7px;border-radius:5px;background:#f3f6fb;color:var(--text-muted);font-size:.68rem}.statistics{display:flex;flex-wrap:wrap;gap:12px;color:var(--text-muted);font-size:.76rem}.statistics b{color:var(--ink-900,#10213d)}.statistics .failed,.statistics .failed b{color:var(--color-danger)}.source-status{display:grid;gap:3px;color:var(--text-muted);font-size:.72rem}.source-status strong{font-size:.72rem}.status-idle,.status-completed{color:var(--color-success)}.status-scanning{color:var(--color-primary)}.status-completed_with_errors,.status-unavailable{color:var(--color-danger)}.source-status em{color:var(--color-danger);font-style:normal}.source-actions{display:flex;align-items:center;gap:10px}.source-actions button{border:1px solid var(--border-subtle);border-radius:7px;padding:6px 9px;background:#fff;color:var(--color-primary);font:inherit;font-size:.76rem;font-weight:700}.source-actions button:disabled{opacity:.55}.document-link{border:0!important;padding:6px 0!important}.remove-action{color:var(--text-muted)!important}.switch input{position:absolute;opacity:0}.switch span{display:block;width:36px;height:20px;border-radius:999px;background:#d3dce8;position:relative}.switch span::after{position:absolute;top:2px;left:2px;width:16px;height:16px;border-radius:50%;background:#fff;box-shadow:0 1px 2px rgba(0,0,0,.15);content:""}.switch input:checked+span{background:var(--color-primary)}.switch input:checked+span::after{transform:translateX(16px)}.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}.empty-state{margin:0;padding:32px 0;color:var(--text-muted);text-align:center}@media(max-width:1050px){.source-row{grid-template-columns:1fr 1fr}.source-actions{justify-content:flex-end}}@media(max-width:650px){.source-row{grid-template-columns:1fr}.source-actions{justify-content:flex-start}}
</style>
