<script setup lang="ts">
import type { KnowledgeSource } from "../../api/knowledgeSources";
defineProps<{ sources: readonly KnowledgeSource[]; disabled: boolean }>();
const emit = defineEmits<{ toggle: [source: KnowledgeSource, enabled: boolean]; remove: [source: KnowledgeSource]; sync: [source: KnowledgeSource] }>();
const typeLabels = { local_folder: "本地文件夹", obsidian_vault: "Obsidian 知识库", temporary_import: "临时导入" };
const statusLabels = { idle: "可同步", scanning: "同步中", completed: "已同步", completed_with_errors: "部分完成", unavailable: "不可用" };
function formatTime(value: string | null) { return value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "尚未同步"; }
</script>
<template>
  <p v-if="sources.length === 0" class="empty-state">还没有知识源。添加目录后，系统只会访问你明确授权的路径。</p>
  <ul v-else class="source-list"><li v-for="source in sources" :key="source.id" class="source-card"><div class="source-main"><span class="type-label">{{ typeLabels[source.source_type] }}</span><div><h3 class="source-name">{{ source.name }}</h3><p class="source-path">{{ source.root_path }}</p></div></div><div class="source-state"><span class="status" :class="`status-${source.sync_status}`">● {{ statusLabels[source.sync_status] }}</span><span class="sync-time" :role="source.error_message ? 'alert' : undefined">{{ source.error_message || `最近同步：${formatTime(source.last_sync_time)}` }}</span></div><div class="source-actions"><button type="button" :disabled="disabled || source.sync_status === 'scanning' || !source.enabled" @click="emit('sync', source)">{{ source.sync_status === 'scanning' ? "同步中" : "同步" }}</button><label class="switch"><input type="checkbox" :checked="source.enabled" :disabled="disabled" @change="emit('toggle', source, ($event.target as HTMLInputElement).checked)" /><span></span><b>{{ source.enabled ? "已启用" : "已停用" }}</b></label><button class="remove-action" type="button" :disabled="disabled" @click="emit('remove', source)">移除</button></div></li></ul>
</template>
<style scoped>
.source-list{margin:0;padding:0;list-style:none;border:1px solid var(--border-subtle);border-radius:10px;overflow:hidden}.source-card{display:grid;grid-template-columns:minmax(250px,1.25fr) minmax(180px,.9fr) auto;gap:1rem;align-items:center;padding:1rem;background:#fff}.source-card+.source-card{border-top:1px solid var(--border-subtle)}.source-main{display:flex;gap:.7rem;align-items:flex-start}.type-label{flex:0 0 auto;padding:.2rem .45rem;border-radius:5px;background:var(--color-primary-soft);color:var(--color-primary);font-size:.72rem;font-weight:700}.source-name{margin:0;color:#10213d;font-size:1rem}.source-path,.sync-time{margin:.15rem 0 0;color:var(--text-muted);font-size:.8rem;overflow-wrap:anywhere}.status{font-size:.84rem;font-weight:700}.status-idle,.status-completed{color:var(--color-success)}.status-scanning{color:var(--color-primary)}.status-unavailable,.status-completed_with_errors{color:var(--color-danger)}.source-actions{display:flex;align-items:center;gap:.65rem}.source-actions button{border:1px solid var(--border-strong);border-radius:7px;padding:.42rem .75rem;background:#fff;color:var(--color-primary);font:inherit;font-weight:700}.remove-action{color:var(--color-danger)!important}.switch{display:flex;align-items:center;gap:.35rem;color:var(--text-muted);font-size:.76rem}.switch input{position:absolute;opacity:0}.switch span{width:34px;height:20px;border-radius:99px;background:#cbd5e1;position:relative}.switch span:after{content:"";position:absolute;top:3px;left:3px;width:14px;height:14px;border-radius:50%;background:#fff;transition:transform .15s ease}.switch input:checked+span{background:var(--color-primary)}.switch input:checked+span:after{transform:translateX(14px)}.switch b{font-weight:600}.empty-state{margin:0;padding:2rem;border:1px dashed var(--border-strong);border-radius:10px;color:var(--text-muted);text-align:center}@media(max-width:800px){.source-card{grid-template-columns:1fr}.source-actions{justify-content:flex-start}}
</style>
