<script setup lang="ts">
import { computed, onMounted, reactive, shallowRef } from "vue";
import { healthApi, type HealthStatus } from "../../api/health";
import { modelConfigsApi, type ModelConfig } from "../../api/modelConfigs";
import ModelConfigCard from "../../components/settings/ModelConfigCard.vue";
const tabs = ["模型", "隐私", "数据", "界面", "系统", "关于"]; const active = shallowRef("模型"); const items = shallowRef<ModelConfig[]>([]); const health = shallowRef<HealthStatus | null>(null); const message = shallowRef(""); const error = shallowRef("");
const form = reactive({ deployment_mode: "local" as "local" | "cloud" | "hybrid", provider: "ollama" as "ollama" | "openai" | "openrouter", api_base: "http://localhost:11434", api_key: "", model_name: "", is_default: true, allow_cloud_content: false });
const needsKey = computed(() => form.provider !== "ollama");
async function load() { try { items.value = await modelConfigsApi.list(); health.value = await healthApi.get(); } catch (cause) { error.value = cause instanceof Error ? cause.message : "无法读取设置"; } }
async function save() { error.value = ""; message.value = ""; try { await modelConfigsApi.create({ ...form }); form.api_key = ""; message.value = "配置已保存；密钥不会再次显示。"; await load(); } catch (cause) { error.value = cause instanceof Error ? cause.message : "保存失败"; } }
async function test(item: ModelConfig) { try { const result = await modelConfigsApi.test(item.id, item.provider !== "ollama"); message.value = result.message; } catch (cause) { error.value = cause instanceof Error ? cause.message : "连接测试失败"; } }
async function remove(id: number) { if (!confirm("删除此模型配置？此操作不会显示或恢复密钥。")) return; await modelConfigsApi.remove(id); await load(); }
onMounted(load);
</script>
<template><main class="settings"><header class="header"><div><p class="eyebrow">SETTINGS CENTER · LIVE</p><h1>设置中心</h1><p>模型配置使用现有真实接口；密钥只可输入和掩码显示，绝不回显完整内容。</p></div><span class="health">{{ health ? `系统 ${health.status}` : "正在读取系统状态" }}</span></header><nav class="tabs" aria-label="设置分类"><button v-for="tab in tabs" :key="tab" :class="{ active: active === tab }" @click="active = tab">{{ tab }}</button></nav><section v-if="active === '模型'" class="panel"><div class="section-title"><div><p class="eyebrow">MODEL CONFIG · LIVE</p><h2>模型配置</h2></div><span>已有配置 {{ items.length }}</span></div><form @submit.prevent="save"><label>部署模式<select v-model="form.deployment_mode"><option value="local">完全本地</option><option value="cloud">云端</option><option value="hybrid">混合</option></select></label><label>Provider<select v-model="form.provider"><option value="ollama">Ollama</option><option value="openai">OpenAI</option><option value="openrouter">OpenRouter</option></select></label><label>API Base<input v-model.trim="form.api_base" required></label><label>模型名称<input v-model.trim="form.model_name" required></label><label v-if="needsKey">API Key<input v-model="form.api_key" type="password" autocomplete="new-password" placeholder="只输入，保存后不回显"></label><label class="check"><input v-model="form.is_default" type="checkbox">设为默认模型</label><label v-if="form.deployment_mode !== 'local'" class="cloud"><input v-model="form.allow_cloud_content" type="checkbox">我授权将内容发送至所选云端 Provider</label><button class="primary">保存配置</button></form><p v-if="message" class="message">{{ message }}</p><p v-if="error" class="error">{{ error }}</p><div class="configs"><ModelConfigCard v-for="item in items" :key="item.id" :item="item" @test="test" @remove="remove"/></div></section><section v-else-if="active === '隐私'" class="panel"><p class="eyebrow">PRIVACY · LIVE CONFIG</p><h2>隐私与内容外发</h2><div class="privacy-grid"><article><h3>完全本地</h3><p>Ollama 本地配置不会自动切换为云端。</p></article><article><h3>混合 / 云端</h3><p>只有启用明确授权后，模型配置才可保存。</p></article><article><h3>敏感材料</h3><p>请在发送前确认材料适合所选 Provider；此页面不保存原始密钥。</p></article></div></section><section v-else-if="active === '系统'" class="panel"><p class="eyebrow">SYSTEM DIAGNOSTICS · LIVE</p><h2>系统诊断</h2><dl class="diagnostics"><div><dt>后端</dt><dd>{{ health?.status || "未连接" }}</dd></div><div><dt>应用</dt><dd>{{ health?.app || "未提供" }}</dd></div><div><dt>前端</dt><dd>当前前端构建</dd></div><div><dt>数据库 / Ollama / PaperQA2</dt><dd>诊断接口未接入</dd></div></dl></section><section v-else class="panel unavailable"><p class="eyebrow">UNAVAILABLE</p><h2>{{ active }}设置待接入</h2><p>当前没有已验证接口，因此不展示虚构状态或危险操作。</p></section></main></template>
<style scoped>.settings{max-width:1280px;padding:2rem 1.4rem}.header{display:flex;justify-content:space-between;gap:1rem}.eyebrow{margin:0;color:var(--color-primary);font-size:.72rem;font-weight:900;letter-spacing:.12em}.header h1{margin:.25rem 0;font-size:2.3rem}.header p:last-child{color:var(--text-muted)}.health{align-self:start;padding:.45rem .6rem;border-radius:99px;background:var(--surface-muted);color:var(--text-muted);font-size:.84rem}.tabs{display:flex;gap:.4rem;flex-wrap:wrap;margin:1.2rem 0}.tabs button{border:1px solid var(--border-subtle);border-radius:99px;padding:.45rem .7rem;background:var(--paper)}.tabs .active{border-color:var(--color-primary);background:var(--color-primary);color:#fff}.panel{padding:1.15rem;border:1px solid var(--border-subtle);border-radius:var(--radius-md);background:var(--paper)}.section-title{display:flex;justify-content:space-between}.section-title h2,.panel h2{margin:.25rem 0}.section-title span{color:var(--text-muted);font-size:.84rem}form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.75rem;margin:1rem 0}label{display:grid;gap:.3rem;font-size:.85rem;font-weight:750}input,select{padding:.55rem .65rem;border:1px solid var(--border-subtle);border-radius:6px;background:var(--surface-muted)}.check{display:flex;align-items:center;gap:.45rem}.cloud{grid-column:1/-1;padding:.7rem;background:var(--color-warning-soft);color:var(--color-warning)}.primary{border:0;border-radius:6px;background:var(--color-primary);color:#fff;font-weight:800}.message{color:var(--color-primary)}.error{color:var(--color-danger)}.configs{display:grid;gap:.65rem;margin-top:1rem}.privacy-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.8rem;margin-top:1rem}.privacy-grid article{padding:.8rem;border-left:3px solid var(--color-primary);background:var(--surface-muted)}.privacy-grid h3{margin:0}.privacy-grid p,.unavailable p{color:var(--text-muted);line-height:1.55}.diagnostics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem;margin:1rem 0}.diagnostics div{padding:.7rem;background:var(--surface-muted)}dt{color:var(--text-muted);font-size:.8rem;font-weight:800}dd{margin:.2rem 0}@media(max-width:720px){.header{display:block}.health{display:inline-block;margin-top:.6rem}form,.privacy-grid,.diagnostics{grid-template-columns:1fr}}</style>
